// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/document.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

/**
 * Protobuf type {@code org.apache.tika.grpc.v2.Document}
 */
public final class Document extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.apache.tika.grpc.v2.Document)
    DocumentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Document.newBuilder() to construct.
  private Document(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Document() {
    id_ = "";
    contentType_ = "";
    extra_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Document();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_Document_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_Document_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.tika.grpc.v2.Document.class, org.apache.tika.grpc.v2.Document.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <pre>
   * envelope
   * The caller's key for the request: fetch_key on FetchAndParse, correlation_id
   * on ParseBytes, returned unchanged. To identify the parsed bytes, use
   * origin.sha256, which is set when a digester is configured.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * envelope
   * The caller's key for the request: fetch_key on FetchAndParse, correlation_id
   * on ParseBytes, returned unchanged. To identify the parsed bytes, use
   * origin.sha256, which is set when a digester is configured.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contentType_ = "";
  /**
   * <pre>
   * Tika-detected MIME type
   * </pre>
   *
   * <code>string content_type = 2;</code>
   * @return The contentType.
   */
  @java.lang.Override
  public java.lang.String getContentType() {
    java.lang.Object ref = contentType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contentType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Tika-detected MIME type
   * </pre>
   *
   * <code>string content_type = 2;</code>
   * @return The bytes for contentType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentTypeBytes() {
    java.lang.Object ref = contentType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contentType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARSED_AT_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp parsedAt_;
  /**
   * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
   * @return Whether the parsedAt field is set.
   */
  @java.lang.Override
  public boolean hasParsedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
   * @return The parsedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getParsedAt() {
    return parsedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : parsedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getParsedAtOrBuilder() {
    return parsedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : parsedAt_;
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private org.apache.tika.grpc.v2.ParseStatus status_;
  /**
   * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
   * @return The status.
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.ParseStatus getStatus() {
    return status_ == null ? org.apache.tika.grpc.v2.ParseStatus.getDefaultInstance() : status_;
  }
  /**
   * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.ParseStatusOrBuilder getStatusOrBuilder() {
    return status_ == null ? org.apache.tika.grpc.v2.ParseStatus.getDefaultInstance() : status_;
  }

  public static final int ORIGIN_FIELD_NUMBER = 6;
  private org.apache.tika.grpc.v2.SourceOrigin origin_;
  /**
   * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
   * @return Whether the origin field is set.
   */
  @java.lang.Override
  public boolean hasOrigin() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
   * @return The origin.
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.SourceOrigin getOrigin() {
    return origin_ == null ? org.apache.tika.grpc.v2.SourceOrigin.getDefaultInstance() : origin_;
  }
  /**
   * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.SourceOriginOrBuilder getOriginOrBuilder() {
    return origin_ == null ? org.apache.tika.grpc.v2.SourceOrigin.getDefaultInstance() : origin_;
  }

  public static final int METADATA_FIELD_NUMBER = 20;
  private org.apache.tika.grpc.v2.DocumentMetadata metadata_;
  /**
   * <pre>
   * metadata
   * </pre>
   *
   * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * metadata
   * </pre>
   *
   * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.DocumentMetadata getMetadata() {
    return metadata_ == null ? org.apache.tika.grpc.v2.DocumentMetadata.getDefaultInstance() : metadata_;
  }
  /**
   * <pre>
   * metadata
   * </pre>
   *
   * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.DocumentMetadataOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? org.apache.tika.grpc.v2.DocumentMetadata.getDefaultInstance() : metadata_;
  }

  public static final int EXTRA_FIELD_NUMBER = 21;
  @SuppressWarnings("serial")
  private java.util.List<org.apache.tika.grpc.v2.MetadataField> extra_;
  /**
   * <pre>
   * tagged tail: everything not already typed
   * </pre>
   *
   * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
   */
  @java.lang.Override
  public java.util.List<org.apache.tika.grpc.v2.MetadataField> getExtraList() {
    return extra_;
  }
  /**
   * <pre>
   * tagged tail: everything not already typed
   * </pre>
   *
   * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.apache.tika.grpc.v2.MetadataFieldOrBuilder> 
      getExtraOrBuilderList() {
    return extra_;
  }
  /**
   * <pre>
   * tagged tail: everything not already typed
   * </pre>
   *
   * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
   */
  @java.lang.Override
  public int getExtraCount() {
    return extra_.size();
  }
  /**
   * <pre>
   * tagged tail: everything not already typed
   * </pre>
   *
   * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.MetadataField getExtra(int index) {
    return extra_.get(index);
  }
  /**
   * <pre>
   * tagged tail: everything not already typed
   * </pre>
   *
   * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.MetadataFieldOrBuilder getExtraOrBuilder(
      int index) {
    return extra_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contentType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contentType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getParsedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getStatus());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(6, getOrigin());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(20, getMetadata());
    }
    for (int i = 0; i < extra_.size(); i++) {
      output.writeMessage(21, extra_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contentType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contentType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getParsedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getStatus());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getOrigin());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, getMetadata());
    }
    for (int i = 0; i < extra_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, extra_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.tika.grpc.v2.Document)) {
      return super.equals(obj);
    }
    org.apache.tika.grpc.v2.Document other = (org.apache.tika.grpc.v2.Document) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getContentType()
        .equals(other.getContentType())) return false;
    if (hasParsedAt() != other.hasParsedAt()) return false;
    if (hasParsedAt()) {
      if (!getParsedAt()
          .equals(other.getParsedAt())) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (hasOrigin() != other.hasOrigin()) return false;
    if (hasOrigin()) {
      if (!getOrigin()
          .equals(other.getOrigin())) return false;
    }
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!getExtraList()
        .equals(other.getExtraList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CONTENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getContentType().hashCode();
    if (hasParsedAt()) {
      hash = (37 * hash) + PARSED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getParsedAt().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasOrigin()) {
      hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
      hash = (53 * hash) + getOrigin().hashCode();
    }
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    if (getExtraCount() > 0) {
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtraList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.tika.grpc.v2.Document parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.Document parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.Document parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.Document parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.Document parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.Document parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.Document parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.Document parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.apache.tika.grpc.v2.Document parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.apache.tika.grpc.v2.Document parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.Document parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.Document parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.tika.grpc.v2.Document prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.apache.tika.grpc.v2.Document}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.apache.tika.grpc.v2.Document)
      org.apache.tika.grpc.v2.DocumentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_Document_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_Document_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.tika.grpc.v2.Document.class, org.apache.tika.grpc.v2.Document.Builder.class);
    }

    // Construct using org.apache.tika.grpc.v2.Document.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getParsedAtFieldBuilder();
        getStatusFieldBuilder();
        getOriginFieldBuilder();
        getMetadataFieldBuilder();
        getExtraFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      contentType_ = "";
      parsedAt_ = null;
      if (parsedAtBuilder_ != null) {
        parsedAtBuilder_.dispose();
        parsedAtBuilder_ = null;
      }
      status_ = null;
      if (statusBuilder_ != null) {
        statusBuilder_.dispose();
        statusBuilder_ = null;
      }
      origin_ = null;
      if (originBuilder_ != null) {
        originBuilder_.dispose();
        originBuilder_ = null;
      }
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      if (extraBuilder_ == null) {
        extra_ = java.util.Collections.emptyList();
      } else {
        extra_ = null;
        extraBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_Document_descriptor;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.Document getDefaultInstanceForType() {
      return org.apache.tika.grpc.v2.Document.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.Document build() {
      org.apache.tika.grpc.v2.Document result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.Document buildPartial() {
      org.apache.tika.grpc.v2.Document result = new org.apache.tika.grpc.v2.Document(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.apache.tika.grpc.v2.Document result) {
      if (extraBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          extra_ = java.util.Collections.unmodifiableList(extra_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.extra_ = extra_;
      } else {
        result.extra_ = extraBuilder_.build();
      }
    }

    private void buildPartial0(org.apache.tika.grpc.v2.Document result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.contentType_ = contentType_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.parsedAt_ = parsedAtBuilder_ == null
            ? parsedAt_
            : parsedAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.status_ = statusBuilder_ == null
            ? status_
            : statusBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.origin_ = originBuilder_ == null
            ? origin_
            : originBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.tika.grpc.v2.Document) {
        return mergeFrom((org.apache.tika.grpc.v2.Document)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.tika.grpc.v2.Document other) {
      if (other == org.apache.tika.grpc.v2.Document.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getContentType().isEmpty()) {
        contentType_ = other.contentType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasParsedAt()) {
        mergeParsedAt(other.getParsedAt());
      }
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.hasOrigin()) {
        mergeOrigin(other.getOrigin());
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      if (extraBuilder_ == null) {
        if (!other.extra_.isEmpty()) {
          if (extra_.isEmpty()) {
            extra_ = other.extra_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureExtraIsMutable();
            extra_.addAll(other.extra_);
          }
          onChanged();
        }
      } else {
        if (!other.extra_.isEmpty()) {
          if (extraBuilder_.isEmpty()) {
            extraBuilder_.dispose();
            extraBuilder_ = null;
            extra_ = other.extra_;
            bitField0_ = (bitField0_ & ~0x00000040);
            extraBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExtraFieldBuilder() : null;
          } else {
            extraBuilder_.addAllMessages(other.extra_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              contentType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 34: {
              input.readMessage(
                  getParsedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getStatusFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getOriginFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 50
            case 162: {
              input.readMessage(
                  getMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 162
            case 170: {
              org.apache.tika.grpc.v2.MetadataField m =
                  input.readMessage(
                      org.apache.tika.grpc.v2.MetadataField.parser(),
                      extensionRegistry);
              if (extraBuilder_ == null) {
                ensureExtraIsMutable();
                extra_.add(m);
              } else {
                extraBuilder_.addMessage(m);
              }
              break;
            } // case 170
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * envelope
     * The caller's key for the request: fetch_key on FetchAndParse, correlation_id
     * on ParseBytes, returned unchanged. To identify the parsed bytes, use
     * origin.sha256, which is set when a digester is configured.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * envelope
     * The caller's key for the request: fetch_key on FetchAndParse, correlation_id
     * on ParseBytes, returned unchanged. To identify the parsed bytes, use
     * origin.sha256, which is set when a digester is configured.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * envelope
     * The caller's key for the request: fetch_key on FetchAndParse, correlation_id
     * on ParseBytes, returned unchanged. To identify the parsed bytes, use
     * origin.sha256, which is set when a digester is configured.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * envelope
     * The caller's key for the request: fetch_key on FetchAndParse, correlation_id
     * on ParseBytes, returned unchanged. To identify the parsed bytes, use
     * origin.sha256, which is set when a digester is configured.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * envelope
     * The caller's key for the request: fetch_key on FetchAndParse, correlation_id
     * on ParseBytes, returned unchanged. To identify the parsed bytes, use
     * origin.sha256, which is set when a digester is configured.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object contentType_ = "";
    /**
     * <pre>
     * Tika-detected MIME type
     * </pre>
     *
     * <code>string content_type = 2;</code>
     * @return The contentType.
     */
    public java.lang.String getContentType() {
      java.lang.Object ref = contentType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Tika-detected MIME type
     * </pre>
     *
     * <code>string content_type = 2;</code>
     * @return The bytes for contentType.
     */
    public com.google.protobuf.ByteString
        getContentTypeBytes() {
      java.lang.Object ref = contentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Tika-detected MIME type
     * </pre>
     *
     * <code>string content_type = 2;</code>
     * @param value The contentType to set.
     * @return This builder for chaining.
     */
    public Builder setContentType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contentType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tika-detected MIME type
     * </pre>
     *
     * <code>string content_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContentType() {
      contentType_ = getDefaultInstance().getContentType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tika-detected MIME type
     * </pre>
     *
     * <code>string content_type = 2;</code>
     * @param value The bytes for contentType to set.
     * @return This builder for chaining.
     */
    public Builder setContentTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contentType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp parsedAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> parsedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
     * @return Whether the parsedAt field is set.
     */
    public boolean hasParsedAt() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
     * @return The parsedAt.
     */
    public com.google.protobuf.Timestamp getParsedAt() {
      if (parsedAtBuilder_ == null) {
        return parsedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : parsedAt_;
      } else {
        return parsedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
     */
    public Builder setParsedAt(com.google.protobuf.Timestamp value) {
      if (parsedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        parsedAt_ = value;
      } else {
        parsedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
     */
    public Builder setParsedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (parsedAtBuilder_ == null) {
        parsedAt_ = builderForValue.build();
      } else {
        parsedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
     */
    public Builder mergeParsedAt(com.google.protobuf.Timestamp value) {
      if (parsedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          parsedAt_ != null &&
          parsedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getParsedAtBuilder().mergeFrom(value);
        } else {
          parsedAt_ = value;
        }
      } else {
        parsedAtBuilder_.mergeFrom(value);
      }
      if (parsedAt_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
     */
    public Builder clearParsedAt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      parsedAt_ = null;
      if (parsedAtBuilder_ != null) {
        parsedAtBuilder_.dispose();
        parsedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getParsedAtBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getParsedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getParsedAtOrBuilder() {
      if (parsedAtBuilder_ != null) {
        return parsedAtBuilder_.getMessageOrBuilder();
      } else {
        return parsedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : parsedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getParsedAtFieldBuilder() {
      if (parsedAtBuilder_ == null) {
        parsedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getParsedAt(),
                getParentForChildren(),
                isClean());
        parsedAt_ = null;
      }
      return parsedAtBuilder_;
    }

    private org.apache.tika.grpc.v2.ParseStatus status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.ParseStatus, org.apache.tika.grpc.v2.ParseStatus.Builder, org.apache.tika.grpc.v2.ParseStatusOrBuilder> statusBuilder_;
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
     * @return The status.
     */
    public org.apache.tika.grpc.v2.ParseStatus getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? org.apache.tika.grpc.v2.ParseStatus.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
     */
    public Builder setStatus(org.apache.tika.grpc.v2.ParseStatus value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
      } else {
        statusBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
     */
    public Builder setStatus(
        org.apache.tika.grpc.v2.ParseStatus.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
     */
    public Builder mergeStatus(org.apache.tika.grpc.v2.ParseStatus value) {
      if (statusBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          status_ != null &&
          status_ != org.apache.tika.grpc.v2.ParseStatus.getDefaultInstance()) {
          getStatusBuilder().mergeFrom(value);
        } else {
          status_ = value;
        }
      } else {
        statusBuilder_.mergeFrom(value);
      }
      if (status_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000008);
      status_ = null;
      if (statusBuilder_ != null) {
        statusBuilder_.dispose();
        statusBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
     */
    public org.apache.tika.grpc.v2.ParseStatus.Builder getStatusBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
     */
    public org.apache.tika.grpc.v2.ParseStatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            org.apache.tika.grpc.v2.ParseStatus.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.ParseStatus, org.apache.tika.grpc.v2.ParseStatus.Builder, org.apache.tika.grpc.v2.ParseStatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.tika.grpc.v2.ParseStatus, org.apache.tika.grpc.v2.ParseStatus.Builder, org.apache.tika.grpc.v2.ParseStatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private org.apache.tika.grpc.v2.SourceOrigin origin_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.SourceOrigin, org.apache.tika.grpc.v2.SourceOrigin.Builder, org.apache.tika.grpc.v2.SourceOriginOrBuilder> originBuilder_;
    /**
     * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
     * @return Whether the origin field is set.
     */
    public boolean hasOrigin() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
     * @return The origin.
     */
    public org.apache.tika.grpc.v2.SourceOrigin getOrigin() {
      if (originBuilder_ == null) {
        return origin_ == null ? org.apache.tika.grpc.v2.SourceOrigin.getDefaultInstance() : origin_;
      } else {
        return originBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
     */
    public Builder setOrigin(org.apache.tika.grpc.v2.SourceOrigin value) {
      if (originBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        origin_ = value;
      } else {
        originBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
     */
    public Builder setOrigin(
        org.apache.tika.grpc.v2.SourceOrigin.Builder builderForValue) {
      if (originBuilder_ == null) {
        origin_ = builderForValue.build();
      } else {
        originBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
     */
    public Builder mergeOrigin(org.apache.tika.grpc.v2.SourceOrigin value) {
      if (originBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          origin_ != null &&
          origin_ != org.apache.tika.grpc.v2.SourceOrigin.getDefaultInstance()) {
          getOriginBuilder().mergeFrom(value);
        } else {
          origin_ = value;
        }
      } else {
        originBuilder_.mergeFrom(value);
      }
      if (origin_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
     */
    public Builder clearOrigin() {
      bitField0_ = (bitField0_ & ~0x00000010);
      origin_ = null;
      if (originBuilder_ != null) {
        originBuilder_.dispose();
        originBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
     */
    public org.apache.tika.grpc.v2.SourceOrigin.Builder getOriginBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getOriginFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
     */
    public org.apache.tika.grpc.v2.SourceOriginOrBuilder getOriginOrBuilder() {
      if (originBuilder_ != null) {
        return originBuilder_.getMessageOrBuilder();
      } else {
        return origin_ == null ?
            org.apache.tika.grpc.v2.SourceOrigin.getDefaultInstance() : origin_;
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.SourceOrigin, org.apache.tika.grpc.v2.SourceOrigin.Builder, org.apache.tika.grpc.v2.SourceOriginOrBuilder> 
        getOriginFieldBuilder() {
      if (originBuilder_ == null) {
        originBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.tika.grpc.v2.SourceOrigin, org.apache.tika.grpc.v2.SourceOrigin.Builder, org.apache.tika.grpc.v2.SourceOriginOrBuilder>(
                getOrigin(),
                getParentForChildren(),
                isClean());
        origin_ = null;
      }
      return originBuilder_;
    }

    private org.apache.tika.grpc.v2.DocumentMetadata metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.DocumentMetadata, org.apache.tika.grpc.v2.DocumentMetadata.Builder, org.apache.tika.grpc.v2.DocumentMetadataOrBuilder> metadataBuilder_;
    /**
     * <pre>
     * metadata
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * metadata
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
     * @return The metadata.
     */
    public org.apache.tika.grpc.v2.DocumentMetadata getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? org.apache.tika.grpc.v2.DocumentMetadata.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * metadata
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
     */
    public Builder setMetadata(org.apache.tika.grpc.v2.DocumentMetadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * metadata
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
     */
    public Builder setMetadata(
        org.apache.tika.grpc.v2.DocumentMetadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * metadata
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
     */
    public Builder mergeMetadata(org.apache.tika.grpc.v2.DocumentMetadata value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          metadata_ != null &&
          metadata_ != org.apache.tika.grpc.v2.DocumentMetadata.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      if (metadata_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * metadata
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000020);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * metadata
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
     */
    public org.apache.tika.grpc.v2.DocumentMetadata.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * metadata
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
     */
    public org.apache.tika.grpc.v2.DocumentMetadataOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            org.apache.tika.grpc.v2.DocumentMetadata.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <pre>
     * metadata
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.DocumentMetadata, org.apache.tika.grpc.v2.DocumentMetadata.Builder, org.apache.tika.grpc.v2.DocumentMetadataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.tika.grpc.v2.DocumentMetadata, org.apache.tika.grpc.v2.DocumentMetadata.Builder, org.apache.tika.grpc.v2.DocumentMetadataOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private java.util.List<org.apache.tika.grpc.v2.MetadataField> extra_ =
      java.util.Collections.emptyList();
    private void ensureExtraIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        extra_ = new java.util.ArrayList<org.apache.tika.grpc.v2.MetadataField>(extra_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.tika.grpc.v2.MetadataField, org.apache.tika.grpc.v2.MetadataField.Builder, org.apache.tika.grpc.v2.MetadataFieldOrBuilder> extraBuilder_;

    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public java.util.List<org.apache.tika.grpc.v2.MetadataField> getExtraList() {
      if (extraBuilder_ == null) {
        return java.util.Collections.unmodifiableList(extra_);
      } else {
        return extraBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public int getExtraCount() {
      if (extraBuilder_ == null) {
        return extra_.size();
      } else {
        return extraBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public org.apache.tika.grpc.v2.MetadataField getExtra(int index) {
      if (extraBuilder_ == null) {
        return extra_.get(index);
      } else {
        return extraBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public Builder setExtra(
        int index, org.apache.tika.grpc.v2.MetadataField value) {
      if (extraBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtraIsMutable();
        extra_.set(index, value);
        onChanged();
      } else {
        extraBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public Builder setExtra(
        int index, org.apache.tika.grpc.v2.MetadataField.Builder builderForValue) {
      if (extraBuilder_ == null) {
        ensureExtraIsMutable();
        extra_.set(index, builderForValue.build());
        onChanged();
      } else {
        extraBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public Builder addExtra(org.apache.tika.grpc.v2.MetadataField value) {
      if (extraBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtraIsMutable();
        extra_.add(value);
        onChanged();
      } else {
        extraBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public Builder addExtra(
        int index, org.apache.tika.grpc.v2.MetadataField value) {
      if (extraBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtraIsMutable();
        extra_.add(index, value);
        onChanged();
      } else {
        extraBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public Builder addExtra(
        org.apache.tika.grpc.v2.MetadataField.Builder builderForValue) {
      if (extraBuilder_ == null) {
        ensureExtraIsMutable();
        extra_.add(builderForValue.build());
        onChanged();
      } else {
        extraBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public Builder addExtra(
        int index, org.apache.tika.grpc.v2.MetadataField.Builder builderForValue) {
      if (extraBuilder_ == null) {
        ensureExtraIsMutable();
        extra_.add(index, builderForValue.build());
        onChanged();
      } else {
        extraBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public Builder addAllExtra(
        java.lang.Iterable<? extends org.apache.tika.grpc.v2.MetadataField> values) {
      if (extraBuilder_ == null) {
        ensureExtraIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, extra_);
        onChanged();
      } else {
        extraBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public Builder clearExtra() {
      if (extraBuilder_ == null) {
        extra_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        extraBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public Builder removeExtra(int index) {
      if (extraBuilder_ == null) {
        ensureExtraIsMutable();
        extra_.remove(index);
        onChanged();
      } else {
        extraBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public org.apache.tika.grpc.v2.MetadataField.Builder getExtraBuilder(
        int index) {
      return getExtraFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public org.apache.tika.grpc.v2.MetadataFieldOrBuilder getExtraOrBuilder(
        int index) {
      if (extraBuilder_ == null) {
        return extra_.get(index);  } else {
        return extraBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public java.util.List<? extends org.apache.tika.grpc.v2.MetadataFieldOrBuilder> 
         getExtraOrBuilderList() {
      if (extraBuilder_ != null) {
        return extraBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(extra_);
      }
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public org.apache.tika.grpc.v2.MetadataField.Builder addExtraBuilder() {
      return getExtraFieldBuilder().addBuilder(
          org.apache.tika.grpc.v2.MetadataField.getDefaultInstance());
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public org.apache.tika.grpc.v2.MetadataField.Builder addExtraBuilder(
        int index) {
      return getExtraFieldBuilder().addBuilder(
          index, org.apache.tika.grpc.v2.MetadataField.getDefaultInstance());
    }
    /**
     * <pre>
     * tagged tail: everything not already typed
     * </pre>
     *
     * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
     */
    public java.util.List<org.apache.tika.grpc.v2.MetadataField.Builder> 
         getExtraBuilderList() {
      return getExtraFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.tika.grpc.v2.MetadataField, org.apache.tika.grpc.v2.MetadataField.Builder, org.apache.tika.grpc.v2.MetadataFieldOrBuilder> 
        getExtraFieldBuilder() {
      if (extraBuilder_ == null) {
        extraBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.apache.tika.grpc.v2.MetadataField, org.apache.tika.grpc.v2.MetadataField.Builder, org.apache.tika.grpc.v2.MetadataFieldOrBuilder>(
                extra_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        extra_ = null;
      }
      return extraBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.apache.tika.grpc.v2.Document)
  }

  // @@protoc_insertion_point(class_scope:org.apache.tika.grpc.v2.Document)
  private static final org.apache.tika.grpc.v2.Document DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.tika.grpc.v2.Document();
  }

  public static org.apache.tika.grpc.v2.Document getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Document>
      PARSER = new com.google.protobuf.AbstractParser<Document>() {
    @java.lang.Override
    public Document parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Document> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Document> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.tika.grpc.v2.Document getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

