// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/document.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

/**
 * <pre>
 * =========================================================================
 * Metadata: typed common fields from the Dublin Core element set (title, creator,
 * description, subject, language, publisher, identifier, date, rights), the same
 * vocabulary Tika's property model and XMP use. Narrower keys (page counts,
 * dimensions, format-specific keys) go to `extra` with their declared type.
 * =========================================================================
 * </pre>
 *
 * Protobuf type {@code org.apache.tika.grpc.v2.DocumentMetadata}
 */
public final class DocumentMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.apache.tika.grpc.v2.DocumentMetadata)
    DocumentMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DocumentMetadata.newBuilder() to construct.
  private DocumentMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DocumentMetadata() {
    title_ = "";
    authors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    description_ = "";
    keywords_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    languages_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    publishers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    identifiers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    rights_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DocumentMetadata();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_DocumentMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_DocumentMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.tika.grpc.v2.DocumentMetadata.class, org.apache.tika.grpc.v2.DocumentMetadata.Builder.class);
  }

  private int bitField0_;
  public static final int TITLE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHORS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList authors_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string authors = 2;</code>
   * @return A list containing the authors.
   */
  public com.google.protobuf.ProtocolStringList
      getAuthorsList() {
    return authors_;
  }
  /**
   * <code>repeated string authors = 2;</code>
   * @return The count of authors.
   */
  public int getAuthorsCount() {
    return authors_.size();
  }
  /**
   * <code>repeated string authors = 2;</code>
   * @param index The index of the element to return.
   * @return The authors at the given index.
   */
  public java.lang.String getAuthors(int index) {
    return authors_.get(index);
  }
  /**
   * <code>repeated string authors = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the authors at the given index.
   */
  public com.google.protobuf.ByteString
      getAuthorsBytes(int index) {
    return authors_.getByteString(index);
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEYWORDS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList keywords_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string keywords = 4;</code>
   * @return A list containing the keywords.
   */
  public com.google.protobuf.ProtocolStringList
      getKeywordsList() {
    return keywords_;
  }
  /**
   * <code>repeated string keywords = 4;</code>
   * @return The count of keywords.
   */
  public int getKeywordsCount() {
    return keywords_.size();
  }
  /**
   * <code>repeated string keywords = 4;</code>
   * @param index The index of the element to return.
   * @return The keywords at the given index.
   */
  public java.lang.String getKeywords(int index) {
    return keywords_.get(index);
  }
  /**
   * <code>repeated string keywords = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the keywords at the given index.
   */
  public com.google.protobuf.ByteString
      getKeywordsBytes(int index) {
    return keywords_.getByteString(index);
  }

  public static final int LANGUAGES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList languages_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string languages = 5;</code>
   * @return A list containing the languages.
   */
  public com.google.protobuf.ProtocolStringList
      getLanguagesList() {
    return languages_;
  }
  /**
   * <code>repeated string languages = 5;</code>
   * @return The count of languages.
   */
  public int getLanguagesCount() {
    return languages_.size();
  }
  /**
   * <code>repeated string languages = 5;</code>
   * @param index The index of the element to return.
   * @return The languages at the given index.
   */
  public java.lang.String getLanguages(int index) {
    return languages_.get(index);
  }
  /**
   * <code>repeated string languages = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the languages at the given index.
   */
  public com.google.protobuf.ByteString
      getLanguagesBytes(int index) {
    return languages_.getByteString(index);
  }

  public static final int PUBLISHERS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList publishers_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string publishers = 6;</code>
   * @return A list containing the publishers.
   */
  public com.google.protobuf.ProtocolStringList
      getPublishersList() {
    return publishers_;
  }
  /**
   * <code>repeated string publishers = 6;</code>
   * @return The count of publishers.
   */
  public int getPublishersCount() {
    return publishers_.size();
  }
  /**
   * <code>repeated string publishers = 6;</code>
   * @param index The index of the element to return.
   * @return The publishers at the given index.
   */
  public java.lang.String getPublishers(int index) {
    return publishers_.get(index);
  }
  /**
   * <code>repeated string publishers = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the publishers at the given index.
   */
  public com.google.protobuf.ByteString
      getPublishersBytes(int index) {
    return publishers_.getByteString(index);
  }

  public static final int IDENTIFIERS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList identifiers_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Unambiguous references to the resource as declared by the document itself
   * (DOI, ISBN, ...), from dc:identifier.
   * </pre>
   *
   * <code>repeated string identifiers = 7;</code>
   * @return A list containing the identifiers.
   */
  public com.google.protobuf.ProtocolStringList
      getIdentifiersList() {
    return identifiers_;
  }
  /**
   * <pre>
   * Unambiguous references to the resource as declared by the document itself
   * (DOI, ISBN, ...), from dc:identifier.
   * </pre>
   *
   * <code>repeated string identifiers = 7;</code>
   * @return The count of identifiers.
   */
  public int getIdentifiersCount() {
    return identifiers_.size();
  }
  /**
   * <pre>
   * Unambiguous references to the resource as declared by the document itself
   * (DOI, ISBN, ...), from dc:identifier.
   * </pre>
   *
   * <code>repeated string identifiers = 7;</code>
   * @param index The index of the element to return.
   * @return The identifiers at the given index.
   */
  public java.lang.String getIdentifiers(int index) {
    return identifiers_.get(index);
  }
  /**
   * <pre>
   * Unambiguous references to the resource as declared by the document itself
   * (DOI, ISBN, ...), from dc:identifier.
   * </pre>
   *
   * <code>repeated string identifiers = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the identifiers at the given index.
   */
  public com.google.protobuf.ByteString
      getIdentifiersBytes(int index) {
    return identifiers_.getByteString(index);
  }

  public static final int CREATED_FIELD_NUMBER = 10;
  private com.google.protobuf.Timestamp created_;
  /**
   * <code>.google.protobuf.Timestamp created = 10;</code>
   * @return Whether the created field is set.
   */
  @java.lang.Override
  public boolean hasCreated() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp created = 10;</code>
   * @return The created.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreated() {
    return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
  }
  /**
   * <code>.google.protobuf.Timestamp created = 10;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
    return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
  }

  public static final int MODIFIED_FIELD_NUMBER = 11;
  private com.google.protobuf.Timestamp modified_;
  /**
   * <code>.google.protobuf.Timestamp modified = 11;</code>
   * @return Whether the modified field is set.
   */
  @java.lang.Override
  public boolean hasModified() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp modified = 11;</code>
   * @return The modified.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getModified() {
    return modified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
  }
  /**
   * <code>.google.protobuf.Timestamp modified = 11;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder() {
    return modified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
  }

  public static final int RIGHTS_FIELD_NUMBER = 20;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rights_ = "";
  /**
   * <pre>
   * free-text rights/license statement, from dc:rights
   * </pre>
   *
   * <code>string rights = 20;</code>
   * @return The rights.
   */
  @java.lang.Override
  public java.lang.String getRights() {
    java.lang.Object ref = rights_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rights_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * free-text rights/license statement, from dc:rights
   * </pre>
   *
   * <code>string rights = 20;</code>
   * @return The bytes for rights.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRightsBytes() {
    java.lang.Object ref = rights_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rights_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
    }
    for (int i = 0; i < authors_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, authors_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    for (int i = 0; i < keywords_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, keywords_.getRaw(i));
    }
    for (int i = 0; i < languages_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, languages_.getRaw(i));
    }
    for (int i = 0; i < publishers_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, publishers_.getRaw(i));
    }
    for (int i = 0; i < identifiers_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, identifiers_.getRaw(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(10, getCreated());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(11, getModified());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rights_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 20, rights_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < authors_.size(); i++) {
        dataSize += computeStringSizeNoTag(authors_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAuthorsList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < keywords_.size(); i++) {
        dataSize += computeStringSizeNoTag(keywords_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getKeywordsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < languages_.size(); i++) {
        dataSize += computeStringSizeNoTag(languages_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLanguagesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < publishers_.size(); i++) {
        dataSize += computeStringSizeNoTag(publishers_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPublishersList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < identifiers_.size(); i++) {
        dataSize += computeStringSizeNoTag(identifiers_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getIdentifiersList().size();
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getCreated());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getModified());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rights_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, rights_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.tika.grpc.v2.DocumentMetadata)) {
      return super.equals(obj);
    }
    org.apache.tika.grpc.v2.DocumentMetadata other = (org.apache.tika.grpc.v2.DocumentMetadata) obj;

    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getAuthorsList()
        .equals(other.getAuthorsList())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getKeywordsList()
        .equals(other.getKeywordsList())) return false;
    if (!getLanguagesList()
        .equals(other.getLanguagesList())) return false;
    if (!getPublishersList()
        .equals(other.getPublishersList())) return false;
    if (!getIdentifiersList()
        .equals(other.getIdentifiersList())) return false;
    if (hasCreated() != other.hasCreated()) return false;
    if (hasCreated()) {
      if (!getCreated()
          .equals(other.getCreated())) return false;
    }
    if (hasModified() != other.hasModified()) return false;
    if (hasModified()) {
      if (!getModified()
          .equals(other.getModified())) return false;
    }
    if (!getRights()
        .equals(other.getRights())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    if (getAuthorsCount() > 0) {
      hash = (37 * hash) + AUTHORS_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorsList().hashCode();
    }
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (getKeywordsCount() > 0) {
      hash = (37 * hash) + KEYWORDS_FIELD_NUMBER;
      hash = (53 * hash) + getKeywordsList().hashCode();
    }
    if (getLanguagesCount() > 0) {
      hash = (37 * hash) + LANGUAGES_FIELD_NUMBER;
      hash = (53 * hash) + getLanguagesList().hashCode();
    }
    if (getPublishersCount() > 0) {
      hash = (37 * hash) + PUBLISHERS_FIELD_NUMBER;
      hash = (53 * hash) + getPublishersList().hashCode();
    }
    if (getIdentifiersCount() > 0) {
      hash = (37 * hash) + IDENTIFIERS_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifiersList().hashCode();
    }
    if (hasCreated()) {
      hash = (37 * hash) + CREATED_FIELD_NUMBER;
      hash = (53 * hash) + getCreated().hashCode();
    }
    if (hasModified()) {
      hash = (37 * hash) + MODIFIED_FIELD_NUMBER;
      hash = (53 * hash) + getModified().hashCode();
    }
    hash = (37 * hash) + RIGHTS_FIELD_NUMBER;
    hash = (53 * hash) + getRights().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.tika.grpc.v2.DocumentMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.DocumentMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.DocumentMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.DocumentMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.DocumentMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.DocumentMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.DocumentMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.DocumentMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.apache.tika.grpc.v2.DocumentMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.apache.tika.grpc.v2.DocumentMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.DocumentMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.DocumentMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.tika.grpc.v2.DocumentMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * =========================================================================
   * Metadata: typed common fields from the Dublin Core element set (title, creator,
   * description, subject, language, publisher, identifier, date, rights), the same
   * vocabulary Tika's property model and XMP use. Narrower keys (page counts,
   * dimensions, format-specific keys) go to `extra` with their declared type.
   * =========================================================================
   * </pre>
   *
   * Protobuf type {@code org.apache.tika.grpc.v2.DocumentMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.apache.tika.grpc.v2.DocumentMetadata)
      org.apache.tika.grpc.v2.DocumentMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_DocumentMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_DocumentMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.tika.grpc.v2.DocumentMetadata.class, org.apache.tika.grpc.v2.DocumentMetadata.Builder.class);
    }

    // Construct using org.apache.tika.grpc.v2.DocumentMetadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCreatedFieldBuilder();
        getModifiedFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      title_ = "";
      authors_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      description_ = "";
      keywords_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      languages_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      publishers_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      identifiers_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      created_ = null;
      if (createdBuilder_ != null) {
        createdBuilder_.dispose();
        createdBuilder_ = null;
      }
      modified_ = null;
      if (modifiedBuilder_ != null) {
        modifiedBuilder_.dispose();
        modifiedBuilder_ = null;
      }
      rights_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_DocumentMetadata_descriptor;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.DocumentMetadata getDefaultInstanceForType() {
      return org.apache.tika.grpc.v2.DocumentMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.DocumentMetadata build() {
      org.apache.tika.grpc.v2.DocumentMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.DocumentMetadata buildPartial() {
      org.apache.tika.grpc.v2.DocumentMetadata result = new org.apache.tika.grpc.v2.DocumentMetadata(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.tika.grpc.v2.DocumentMetadata result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        authors_.makeImmutable();
        result.authors_ = authors_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        keywords_.makeImmutable();
        result.keywords_ = keywords_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        languages_.makeImmutable();
        result.languages_ = languages_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        publishers_.makeImmutable();
        result.publishers_ = publishers_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        identifiers_.makeImmutable();
        result.identifiers_ = identifiers_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.created_ = createdBuilder_ == null
            ? created_
            : createdBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.modified_ = modifiedBuilder_ == null
            ? modified_
            : modifiedBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.rights_ = rights_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.tika.grpc.v2.DocumentMetadata) {
        return mergeFrom((org.apache.tika.grpc.v2.DocumentMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.tika.grpc.v2.DocumentMetadata other) {
      if (other == org.apache.tika.grpc.v2.DocumentMetadata.getDefaultInstance()) return this;
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.authors_.isEmpty()) {
        if (authors_.isEmpty()) {
          authors_ = other.authors_;
          bitField0_ |= 0x00000002;
        } else {
          ensureAuthorsIsMutable();
          authors_.addAll(other.authors_);
        }
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.keywords_.isEmpty()) {
        if (keywords_.isEmpty()) {
          keywords_ = other.keywords_;
          bitField0_ |= 0x00000008;
        } else {
          ensureKeywordsIsMutable();
          keywords_.addAll(other.keywords_);
        }
        onChanged();
      }
      if (!other.languages_.isEmpty()) {
        if (languages_.isEmpty()) {
          languages_ = other.languages_;
          bitField0_ |= 0x00000010;
        } else {
          ensureLanguagesIsMutable();
          languages_.addAll(other.languages_);
        }
        onChanged();
      }
      if (!other.publishers_.isEmpty()) {
        if (publishers_.isEmpty()) {
          publishers_ = other.publishers_;
          bitField0_ |= 0x00000020;
        } else {
          ensurePublishersIsMutable();
          publishers_.addAll(other.publishers_);
        }
        onChanged();
      }
      if (!other.identifiers_.isEmpty()) {
        if (identifiers_.isEmpty()) {
          identifiers_ = other.identifiers_;
          bitField0_ |= 0x00000040;
        } else {
          ensureIdentifiersIsMutable();
          identifiers_.addAll(other.identifiers_);
        }
        onChanged();
      }
      if (other.hasCreated()) {
        mergeCreated(other.getCreated());
      }
      if (other.hasModified()) {
        mergeModified(other.getModified());
      }
      if (!other.getRights().isEmpty()) {
        rights_ = other.rights_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureAuthorsIsMutable();
              authors_.add(s);
              break;
            } // case 18
            case 26: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureKeywordsIsMutable();
              keywords_.add(s);
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureLanguagesIsMutable();
              languages_.add(s);
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensurePublishersIsMutable();
              publishers_.add(s);
              break;
            } // case 50
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureIdentifiersIsMutable();
              identifiers_.add(s);
              break;
            } // case 58
            case 82: {
              input.readMessage(
                  getCreatedFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 82
            case 90: {
              input.readMessage(
                  getModifiedFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 90
            case 162: {
              rights_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 162
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 1;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList authors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureAuthorsIsMutable() {
      if (!authors_.isModifiable()) {
        authors_ = new com.google.protobuf.LazyStringArrayList(authors_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string authors = 2;</code>
     * @return A list containing the authors.
     */
    public com.google.protobuf.ProtocolStringList
        getAuthorsList() {
      authors_.makeImmutable();
      return authors_;
    }
    /**
     * <code>repeated string authors = 2;</code>
     * @return The count of authors.
     */
    public int getAuthorsCount() {
      return authors_.size();
    }
    /**
     * <code>repeated string authors = 2;</code>
     * @param index The index of the element to return.
     * @return The authors at the given index.
     */
    public java.lang.String getAuthors(int index) {
      return authors_.get(index);
    }
    /**
     * <code>repeated string authors = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the authors at the given index.
     */
    public com.google.protobuf.ByteString
        getAuthorsBytes(int index) {
      return authors_.getByteString(index);
    }
    /**
     * <code>repeated string authors = 2;</code>
     * @param index The index to set the value at.
     * @param value The authors to set.
     * @return This builder for chaining.
     */
    public Builder setAuthors(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAuthorsIsMutable();
      authors_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string authors = 2;</code>
     * @param value The authors to add.
     * @return This builder for chaining.
     */
    public Builder addAuthors(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAuthorsIsMutable();
      authors_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string authors = 2;</code>
     * @param values The authors to add.
     * @return This builder for chaining.
     */
    public Builder addAllAuthors(
        java.lang.Iterable<java.lang.String> values) {
      ensureAuthorsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, authors_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string authors = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthors() {
      authors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string authors = 2;</code>
     * @param value The bytes of the authors to add.
     * @return This builder for chaining.
     */
    public Builder addAuthorsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureAuthorsIsMutable();
      authors_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList keywords_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureKeywordsIsMutable() {
      if (!keywords_.isModifiable()) {
        keywords_ = new com.google.protobuf.LazyStringArrayList(keywords_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string keywords = 4;</code>
     * @return A list containing the keywords.
     */
    public com.google.protobuf.ProtocolStringList
        getKeywordsList() {
      keywords_.makeImmutable();
      return keywords_;
    }
    /**
     * <code>repeated string keywords = 4;</code>
     * @return The count of keywords.
     */
    public int getKeywordsCount() {
      return keywords_.size();
    }
    /**
     * <code>repeated string keywords = 4;</code>
     * @param index The index of the element to return.
     * @return The keywords at the given index.
     */
    public java.lang.String getKeywords(int index) {
      return keywords_.get(index);
    }
    /**
     * <code>repeated string keywords = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the keywords at the given index.
     */
    public com.google.protobuf.ByteString
        getKeywordsBytes(int index) {
      return keywords_.getByteString(index);
    }
    /**
     * <code>repeated string keywords = 4;</code>
     * @param index The index to set the value at.
     * @param value The keywords to set.
     * @return This builder for chaining.
     */
    public Builder setKeywords(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureKeywordsIsMutable();
      keywords_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string keywords = 4;</code>
     * @param value The keywords to add.
     * @return This builder for chaining.
     */
    public Builder addKeywords(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureKeywordsIsMutable();
      keywords_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string keywords = 4;</code>
     * @param values The keywords to add.
     * @return This builder for chaining.
     */
    public Builder addAllKeywords(
        java.lang.Iterable<java.lang.String> values) {
      ensureKeywordsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, keywords_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string keywords = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeywords() {
      keywords_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string keywords = 4;</code>
     * @param value The bytes of the keywords to add.
     * @return This builder for chaining.
     */
    public Builder addKeywordsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureKeywordsIsMutable();
      keywords_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList languages_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureLanguagesIsMutable() {
      if (!languages_.isModifiable()) {
        languages_ = new com.google.protobuf.LazyStringArrayList(languages_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>repeated string languages = 5;</code>
     * @return A list containing the languages.
     */
    public com.google.protobuf.ProtocolStringList
        getLanguagesList() {
      languages_.makeImmutable();
      return languages_;
    }
    /**
     * <code>repeated string languages = 5;</code>
     * @return The count of languages.
     */
    public int getLanguagesCount() {
      return languages_.size();
    }
    /**
     * <code>repeated string languages = 5;</code>
     * @param index The index of the element to return.
     * @return The languages at the given index.
     */
    public java.lang.String getLanguages(int index) {
      return languages_.get(index);
    }
    /**
     * <code>repeated string languages = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the languages at the given index.
     */
    public com.google.protobuf.ByteString
        getLanguagesBytes(int index) {
      return languages_.getByteString(index);
    }
    /**
     * <code>repeated string languages = 5;</code>
     * @param index The index to set the value at.
     * @param value The languages to set.
     * @return This builder for chaining.
     */
    public Builder setLanguages(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLanguagesIsMutable();
      languages_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string languages = 5;</code>
     * @param value The languages to add.
     * @return This builder for chaining.
     */
    public Builder addLanguages(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLanguagesIsMutable();
      languages_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string languages = 5;</code>
     * @param values The languages to add.
     * @return This builder for chaining.
     */
    public Builder addAllLanguages(
        java.lang.Iterable<java.lang.String> values) {
      ensureLanguagesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, languages_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string languages = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguages() {
      languages_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string languages = 5;</code>
     * @param value The bytes of the languages to add.
     * @return This builder for chaining.
     */
    public Builder addLanguagesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureLanguagesIsMutable();
      languages_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList publishers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensurePublishersIsMutable() {
      if (!publishers_.isModifiable()) {
        publishers_ = new com.google.protobuf.LazyStringArrayList(publishers_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <code>repeated string publishers = 6;</code>
     * @return A list containing the publishers.
     */
    public com.google.protobuf.ProtocolStringList
        getPublishersList() {
      publishers_.makeImmutable();
      return publishers_;
    }
    /**
     * <code>repeated string publishers = 6;</code>
     * @return The count of publishers.
     */
    public int getPublishersCount() {
      return publishers_.size();
    }
    /**
     * <code>repeated string publishers = 6;</code>
     * @param index The index of the element to return.
     * @return The publishers at the given index.
     */
    public java.lang.String getPublishers(int index) {
      return publishers_.get(index);
    }
    /**
     * <code>repeated string publishers = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the publishers at the given index.
     */
    public com.google.protobuf.ByteString
        getPublishersBytes(int index) {
      return publishers_.getByteString(index);
    }
    /**
     * <code>repeated string publishers = 6;</code>
     * @param index The index to set the value at.
     * @param value The publishers to set.
     * @return This builder for chaining.
     */
    public Builder setPublishers(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePublishersIsMutable();
      publishers_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string publishers = 6;</code>
     * @param value The publishers to add.
     * @return This builder for chaining.
     */
    public Builder addPublishers(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePublishersIsMutable();
      publishers_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string publishers = 6;</code>
     * @param values The publishers to add.
     * @return This builder for chaining.
     */
    public Builder addAllPublishers(
        java.lang.Iterable<java.lang.String> values) {
      ensurePublishersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, publishers_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string publishers = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublishers() {
      publishers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string publishers = 6;</code>
     * @param value The bytes of the publishers to add.
     * @return This builder for chaining.
     */
    public Builder addPublishersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensurePublishersIsMutable();
      publishers_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList identifiers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureIdentifiersIsMutable() {
      if (!identifiers_.isModifiable()) {
        identifiers_ = new com.google.protobuf.LazyStringArrayList(identifiers_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <pre>
     * Unambiguous references to the resource as declared by the document itself
     * (DOI, ISBN, ...), from dc:identifier.
     * </pre>
     *
     * <code>repeated string identifiers = 7;</code>
     * @return A list containing the identifiers.
     */
    public com.google.protobuf.ProtocolStringList
        getIdentifiersList() {
      identifiers_.makeImmutable();
      return identifiers_;
    }
    /**
     * <pre>
     * Unambiguous references to the resource as declared by the document itself
     * (DOI, ISBN, ...), from dc:identifier.
     * </pre>
     *
     * <code>repeated string identifiers = 7;</code>
     * @return The count of identifiers.
     */
    public int getIdentifiersCount() {
      return identifiers_.size();
    }
    /**
     * <pre>
     * Unambiguous references to the resource as declared by the document itself
     * (DOI, ISBN, ...), from dc:identifier.
     * </pre>
     *
     * <code>repeated string identifiers = 7;</code>
     * @param index The index of the element to return.
     * @return The identifiers at the given index.
     */
    public java.lang.String getIdentifiers(int index) {
      return identifiers_.get(index);
    }
    /**
     * <pre>
     * Unambiguous references to the resource as declared by the document itself
     * (DOI, ISBN, ...), from dc:identifier.
     * </pre>
     *
     * <code>repeated string identifiers = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the identifiers at the given index.
     */
    public com.google.protobuf.ByteString
        getIdentifiersBytes(int index) {
      return identifiers_.getByteString(index);
    }
    /**
     * <pre>
     * Unambiguous references to the resource as declared by the document itself
     * (DOI, ISBN, ...), from dc:identifier.
     * </pre>
     *
     * <code>repeated string identifiers = 7;</code>
     * @param index The index to set the value at.
     * @param value The identifiers to set.
     * @return This builder for chaining.
     */
    public Builder setIdentifiers(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureIdentifiersIsMutable();
      identifiers_.set(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unambiguous references to the resource as declared by the document itself
     * (DOI, ISBN, ...), from dc:identifier.
     * </pre>
     *
     * <code>repeated string identifiers = 7;</code>
     * @param value The identifiers to add.
     * @return This builder for chaining.
     */
    public Builder addIdentifiers(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureIdentifiersIsMutable();
      identifiers_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unambiguous references to the resource as declared by the document itself
     * (DOI, ISBN, ...), from dc:identifier.
     * </pre>
     *
     * <code>repeated string identifiers = 7;</code>
     * @param values The identifiers to add.
     * @return This builder for chaining.
     */
    public Builder addAllIdentifiers(
        java.lang.Iterable<java.lang.String> values) {
      ensureIdentifiersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, identifiers_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unambiguous references to the resource as declared by the document itself
     * (DOI, ISBN, ...), from dc:identifier.
     * </pre>
     *
     * <code>repeated string identifiers = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentifiers() {
      identifiers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unambiguous references to the resource as declared by the document itself
     * (DOI, ISBN, ...), from dc:identifier.
     * </pre>
     *
     * <code>repeated string identifiers = 7;</code>
     * @param value The bytes of the identifiers to add.
     * @return This builder for chaining.
     */
    public Builder addIdentifiersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureIdentifiersIsMutable();
      identifiers_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp created_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created = 10;</code>
     * @return Whether the created field is set.
     */
    public boolean hasCreated() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created = 10;</code>
     * @return The created.
     */
    public com.google.protobuf.Timestamp getCreated() {
      if (createdBuilder_ == null) {
        return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
      } else {
        return createdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created = 10;</code>
     */
    public Builder setCreated(com.google.protobuf.Timestamp value) {
      if (createdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        created_ = value;
      } else {
        createdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 10;</code>
     */
    public Builder setCreated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdBuilder_ == null) {
        created_ = builderForValue.build();
      } else {
        createdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 10;</code>
     */
    public Builder mergeCreated(com.google.protobuf.Timestamp value) {
      if (createdBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          created_ != null &&
          created_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedBuilder().mergeFrom(value);
        } else {
          created_ = value;
        }
      } else {
        createdBuilder_.mergeFrom(value);
      }
      if (created_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 10;</code>
     */
    public Builder clearCreated() {
      bitField0_ = (bitField0_ & ~0x00000080);
      created_ = null;
      if (createdBuilder_ != null) {
        createdBuilder_.dispose();
        createdBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 10;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getCreatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created = 10;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
      if (createdBuilder_ != null) {
        return createdBuilder_.getMessageOrBuilder();
      } else {
        return created_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : created_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedFieldBuilder() {
      if (createdBuilder_ == null) {
        createdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreated(),
                getParentForChildren(),
                isClean());
        created_ = null;
      }
      return createdBuilder_;
    }

    private com.google.protobuf.Timestamp modified_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> modifiedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp modified = 11;</code>
     * @return Whether the modified field is set.
     */
    public boolean hasModified() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 11;</code>
     * @return The modified.
     */
    public com.google.protobuf.Timestamp getModified() {
      if (modifiedBuilder_ == null) {
        return modified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
      } else {
        return modifiedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 11;</code>
     */
    public Builder setModified(com.google.protobuf.Timestamp value) {
      if (modifiedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        modified_ = value;
      } else {
        modifiedBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 11;</code>
     */
    public Builder setModified(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (modifiedBuilder_ == null) {
        modified_ = builderForValue.build();
      } else {
        modifiedBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 11;</code>
     */
    public Builder mergeModified(com.google.protobuf.Timestamp value) {
      if (modifiedBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          modified_ != null &&
          modified_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getModifiedBuilder().mergeFrom(value);
        } else {
          modified_ = value;
        }
      } else {
        modifiedBuilder_.mergeFrom(value);
      }
      if (modified_ != null) {
        bitField0_ |= 0x00000100;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 11;</code>
     */
    public Builder clearModified() {
      bitField0_ = (bitField0_ & ~0x00000100);
      modified_ = null;
      if (modifiedBuilder_ != null) {
        modifiedBuilder_.dispose();
        modifiedBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 11;</code>
     */
    public com.google.protobuf.Timestamp.Builder getModifiedBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getModifiedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 11;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder() {
      if (modifiedBuilder_ != null) {
        return modifiedBuilder_.getMessageOrBuilder();
      } else {
        return modified_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getModifiedFieldBuilder() {
      if (modifiedBuilder_ == null) {
        modifiedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getModified(),
                getParentForChildren(),
                isClean());
        modified_ = null;
      }
      return modifiedBuilder_;
    }

    private java.lang.Object rights_ = "";
    /**
     * <pre>
     * free-text rights/license statement, from dc:rights
     * </pre>
     *
     * <code>string rights = 20;</code>
     * @return The rights.
     */
    public java.lang.String getRights() {
      java.lang.Object ref = rights_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rights_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * free-text rights/license statement, from dc:rights
     * </pre>
     *
     * <code>string rights = 20;</code>
     * @return The bytes for rights.
     */
    public com.google.protobuf.ByteString
        getRightsBytes() {
      java.lang.Object ref = rights_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rights_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * free-text rights/license statement, from dc:rights
     * </pre>
     *
     * <code>string rights = 20;</code>
     * @param value The rights to set.
     * @return This builder for chaining.
     */
    public Builder setRights(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rights_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * free-text rights/license statement, from dc:rights
     * </pre>
     *
     * <code>string rights = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearRights() {
      rights_ = getDefaultInstance().getRights();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * free-text rights/license statement, from dc:rights
     * </pre>
     *
     * <code>string rights = 20;</code>
     * @param value The bytes for rights to set.
     * @return This builder for chaining.
     */
    public Builder setRightsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rights_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.apache.tika.grpc.v2.DocumentMetadata)
  }

  // @@protoc_insertion_point(class_scope:org.apache.tika.grpc.v2.DocumentMetadata)
  private static final org.apache.tika.grpc.v2.DocumentMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.tika.grpc.v2.DocumentMetadata();
  }

  public static org.apache.tika.grpc.v2.DocumentMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DocumentMetadata>
      PARSER = new com.google.protobuf.AbstractParser<DocumentMetadata>() {
    @java.lang.Override
    public DocumentMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DocumentMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DocumentMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.tika.grpc.v2.DocumentMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

