// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/document.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

public interface DocumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.tika.grpc.v2.Document)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * envelope
   * The caller's key for the request: fetch_key on FetchAndParse, correlation_id
   * on ParseBytes, returned unchanged. To identify the parsed bytes, use
   * origin.sha256, which is set when a digester is configured.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * envelope
   * The caller's key for the request: fetch_key on FetchAndParse, correlation_id
   * on ParseBytes, returned unchanged. To identify the parsed bytes, use
   * origin.sha256, which is set when a digester is configured.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Tika-detected MIME type
   * </pre>
   *
   * <code>string content_type = 2;</code>
   * @return The contentType.
   */
  java.lang.String getContentType();
  /**
   * <pre>
   * Tika-detected MIME type
   * </pre>
   *
   * <code>string content_type = 2;</code>
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();

  /**
   * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
   * @return Whether the parsedAt field is set.
   */
  boolean hasParsedAt();
  /**
   * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
   * @return The parsedAt.
   */
  com.google.protobuf.Timestamp getParsedAt();
  /**
   * <code>.google.protobuf.Timestamp parsed_at = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getParsedAtOrBuilder();

  /**
   * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
   * @return The status.
   */
  org.apache.tika.grpc.v2.ParseStatus getStatus();
  /**
   * <code>.org.apache.tika.grpc.v2.ParseStatus status = 5;</code>
   */
  org.apache.tika.grpc.v2.ParseStatusOrBuilder getStatusOrBuilder();

  /**
   * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
   * @return Whether the origin field is set.
   */
  boolean hasOrigin();
  /**
   * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
   * @return The origin.
   */
  org.apache.tika.grpc.v2.SourceOrigin getOrigin();
  /**
   * <code>.org.apache.tika.grpc.v2.SourceOrigin origin = 6;</code>
   */
  org.apache.tika.grpc.v2.SourceOriginOrBuilder getOriginOrBuilder();

  /**
   * <pre>
   * metadata
   * </pre>
   *
   * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * metadata
   * </pre>
   *
   * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
   * @return The metadata.
   */
  org.apache.tika.grpc.v2.DocumentMetadata getMetadata();
  /**
   * <pre>
   * metadata
   * </pre>
   *
   * <code>.org.apache.tika.grpc.v2.DocumentMetadata metadata = 20;</code>
   */
  org.apache.tika.grpc.v2.DocumentMetadataOrBuilder getMetadataOrBuilder();

  /**
   * <pre>
   * tagged tail: everything not already typed
   * </pre>
   *
   * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
   */
  java.util.List<org.apache.tika.grpc.v2.MetadataField> 
      getExtraList();
  /**
   * <pre>
   * tagged tail: everything not already typed
   * </pre>
   *
   * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
   */
  org.apache.tika.grpc.v2.MetadataField getExtra(int index);
  /**
   * <pre>
   * tagged tail: everything not already typed
   * </pre>
   *
   * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
   */
  int getExtraCount();
  /**
   * <pre>
   * tagged tail: everything not already typed
   * </pre>
   *
   * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
   */
  java.util.List<? extends org.apache.tika.grpc.v2.MetadataFieldOrBuilder> 
      getExtraOrBuilderList();
  /**
   * <pre>
   * tagged tail: everything not already typed
   * </pre>
   *
   * <code>repeated .org.apache.tika.grpc.v2.MetadataField extra = 21;</code>
   */
  org.apache.tika.grpc.v2.MetadataFieldOrBuilder getExtraOrBuilder(
      int index);
}
