// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/document.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

public interface MetadataValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.tika.grpc.v2.MetadataValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * keys without a declared type
   * </pre>
   *
   * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
   * @return Whether the strings field is set.
   */
  boolean hasStrings();
  /**
   * <pre>
   * keys without a declared type
   * </pre>
   *
   * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
   * @return The strings.
   */
  org.apache.tika.grpc.v2.StringValues getStrings();
  /**
   * <pre>
   * keys without a declared type
   * </pre>
   *
   * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
   */
  org.apache.tika.grpc.v2.StringValuesOrBuilder getStringsOrBuilder();

  /**
   * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
   * @return Whether the integers field is set.
   */
  boolean hasIntegers();
  /**
   * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
   * @return The integers.
   */
  org.apache.tika.grpc.v2.IntegerValues getIntegers();
  /**
   * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
   */
  org.apache.tika.grpc.v2.IntegerValuesOrBuilder getIntegersOrBuilder();

  /**
   * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
   * @return Whether the numbers field is set.
   */
  boolean hasNumbers();
  /**
   * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
   * @return The numbers.
   */
  org.apache.tika.grpc.v2.NumberValues getNumbers();
  /**
   * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
   */
  org.apache.tika.grpc.v2.NumberValuesOrBuilder getNumbersOrBuilder();

  /**
   * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
   * @return Whether the booleans field is set.
   */
  boolean hasBooleans();
  /**
   * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
   * @return The booleans.
   */
  org.apache.tika.grpc.v2.BooleanValues getBooleans();
  /**
   * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
   */
  org.apache.tika.grpc.v2.BooleanValuesOrBuilder getBooleansOrBuilder();

  /**
   * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
   * @return Whether the timestamps field is set.
   */
  boolean hasTimestamps();
  /**
   * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
   * @return The timestamps.
   */
  org.apache.tika.grpc.v2.TimestampValues getTimestamps();
  /**
   * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
   */
  org.apache.tika.grpc.v2.TimestampValuesOrBuilder getTimestampsOrBuilder();

  org.apache.tika.grpc.v2.MetadataValue.ValuesCase getValuesCase();
}
