// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/document.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

/**
 * Protobuf type {@code org.apache.tika.grpc.v2.MetadataValue}
 */
public final class MetadataValue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.apache.tika.grpc.v2.MetadataValue)
    MetadataValueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetadataValue.newBuilder() to construct.
  private MetadataValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetadataValue() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MetadataValue();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_MetadataValue_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_MetadataValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.tika.grpc.v2.MetadataValue.class, org.apache.tika.grpc.v2.MetadataValue.Builder.class);
  }

  private int valuesCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object values_;
  public enum ValuesCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    STRINGS(1),
    INTEGERS(2),
    NUMBERS(3),
    BOOLEANS(4),
    TIMESTAMPS(5),
    VALUES_NOT_SET(0);
    private final int value;
    private ValuesCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValuesCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValuesCase forNumber(int value) {
      switch (value) {
        case 1: return STRINGS;
        case 2: return INTEGERS;
        case 3: return NUMBERS;
        case 4: return BOOLEANS;
        case 5: return TIMESTAMPS;
        case 0: return VALUES_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValuesCase
  getValuesCase() {
    return ValuesCase.forNumber(
        valuesCase_);
  }

  public static final int STRINGS_FIELD_NUMBER = 1;
  /**
   * <pre>
   * keys without a declared type
   * </pre>
   *
   * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
   * @return Whether the strings field is set.
   */
  @java.lang.Override
  public boolean hasStrings() {
    return valuesCase_ == 1;
  }
  /**
   * <pre>
   * keys without a declared type
   * </pre>
   *
   * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
   * @return The strings.
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.StringValues getStrings() {
    if (valuesCase_ == 1) {
       return (org.apache.tika.grpc.v2.StringValues) values_;
    }
    return org.apache.tika.grpc.v2.StringValues.getDefaultInstance();
  }
  /**
   * <pre>
   * keys without a declared type
   * </pre>
   *
   * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.StringValuesOrBuilder getStringsOrBuilder() {
    if (valuesCase_ == 1) {
       return (org.apache.tika.grpc.v2.StringValues) values_;
    }
    return org.apache.tika.grpc.v2.StringValues.getDefaultInstance();
  }

  public static final int INTEGERS_FIELD_NUMBER = 2;
  /**
   * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
   * @return Whether the integers field is set.
   */
  @java.lang.Override
  public boolean hasIntegers() {
    return valuesCase_ == 2;
  }
  /**
   * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
   * @return The integers.
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.IntegerValues getIntegers() {
    if (valuesCase_ == 2) {
       return (org.apache.tika.grpc.v2.IntegerValues) values_;
    }
    return org.apache.tika.grpc.v2.IntegerValues.getDefaultInstance();
  }
  /**
   * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.IntegerValuesOrBuilder getIntegersOrBuilder() {
    if (valuesCase_ == 2) {
       return (org.apache.tika.grpc.v2.IntegerValues) values_;
    }
    return org.apache.tika.grpc.v2.IntegerValues.getDefaultInstance();
  }

  public static final int NUMBERS_FIELD_NUMBER = 3;
  /**
   * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
   * @return Whether the numbers field is set.
   */
  @java.lang.Override
  public boolean hasNumbers() {
    return valuesCase_ == 3;
  }
  /**
   * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
   * @return The numbers.
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.NumberValues getNumbers() {
    if (valuesCase_ == 3) {
       return (org.apache.tika.grpc.v2.NumberValues) values_;
    }
    return org.apache.tika.grpc.v2.NumberValues.getDefaultInstance();
  }
  /**
   * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.NumberValuesOrBuilder getNumbersOrBuilder() {
    if (valuesCase_ == 3) {
       return (org.apache.tika.grpc.v2.NumberValues) values_;
    }
    return org.apache.tika.grpc.v2.NumberValues.getDefaultInstance();
  }

  public static final int BOOLEANS_FIELD_NUMBER = 4;
  /**
   * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
   * @return Whether the booleans field is set.
   */
  @java.lang.Override
  public boolean hasBooleans() {
    return valuesCase_ == 4;
  }
  /**
   * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
   * @return The booleans.
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.BooleanValues getBooleans() {
    if (valuesCase_ == 4) {
       return (org.apache.tika.grpc.v2.BooleanValues) values_;
    }
    return org.apache.tika.grpc.v2.BooleanValues.getDefaultInstance();
  }
  /**
   * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.BooleanValuesOrBuilder getBooleansOrBuilder() {
    if (valuesCase_ == 4) {
       return (org.apache.tika.grpc.v2.BooleanValues) values_;
    }
    return org.apache.tika.grpc.v2.BooleanValues.getDefaultInstance();
  }

  public static final int TIMESTAMPS_FIELD_NUMBER = 5;
  /**
   * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
   * @return Whether the timestamps field is set.
   */
  @java.lang.Override
  public boolean hasTimestamps() {
    return valuesCase_ == 5;
  }
  /**
   * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
   * @return The timestamps.
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.TimestampValues getTimestamps() {
    if (valuesCase_ == 5) {
       return (org.apache.tika.grpc.v2.TimestampValues) values_;
    }
    return org.apache.tika.grpc.v2.TimestampValues.getDefaultInstance();
  }
  /**
   * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.TimestampValuesOrBuilder getTimestampsOrBuilder() {
    if (valuesCase_ == 5) {
       return (org.apache.tika.grpc.v2.TimestampValues) values_;
    }
    return org.apache.tika.grpc.v2.TimestampValues.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (valuesCase_ == 1) {
      output.writeMessage(1, (org.apache.tika.grpc.v2.StringValues) values_);
    }
    if (valuesCase_ == 2) {
      output.writeMessage(2, (org.apache.tika.grpc.v2.IntegerValues) values_);
    }
    if (valuesCase_ == 3) {
      output.writeMessage(3, (org.apache.tika.grpc.v2.NumberValues) values_);
    }
    if (valuesCase_ == 4) {
      output.writeMessage(4, (org.apache.tika.grpc.v2.BooleanValues) values_);
    }
    if (valuesCase_ == 5) {
      output.writeMessage(5, (org.apache.tika.grpc.v2.TimestampValues) values_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (valuesCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (org.apache.tika.grpc.v2.StringValues) values_);
    }
    if (valuesCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (org.apache.tika.grpc.v2.IntegerValues) values_);
    }
    if (valuesCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (org.apache.tika.grpc.v2.NumberValues) values_);
    }
    if (valuesCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (org.apache.tika.grpc.v2.BooleanValues) values_);
    }
    if (valuesCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (org.apache.tika.grpc.v2.TimestampValues) values_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.tika.grpc.v2.MetadataValue)) {
      return super.equals(obj);
    }
    org.apache.tika.grpc.v2.MetadataValue other = (org.apache.tika.grpc.v2.MetadataValue) obj;

    if (!getValuesCase().equals(other.getValuesCase())) return false;
    switch (valuesCase_) {
      case 1:
        if (!getStrings()
            .equals(other.getStrings())) return false;
        break;
      case 2:
        if (!getIntegers()
            .equals(other.getIntegers())) return false;
        break;
      case 3:
        if (!getNumbers()
            .equals(other.getNumbers())) return false;
        break;
      case 4:
        if (!getBooleans()
            .equals(other.getBooleans())) return false;
        break;
      case 5:
        if (!getTimestamps()
            .equals(other.getTimestamps())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (valuesCase_) {
      case 1:
        hash = (37 * hash) + STRINGS_FIELD_NUMBER;
        hash = (53 * hash) + getStrings().hashCode();
        break;
      case 2:
        hash = (37 * hash) + INTEGERS_FIELD_NUMBER;
        hash = (53 * hash) + getIntegers().hashCode();
        break;
      case 3:
        hash = (37 * hash) + NUMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getNumbers().hashCode();
        break;
      case 4:
        hash = (37 * hash) + BOOLEANS_FIELD_NUMBER;
        hash = (53 * hash) + getBooleans().hashCode();
        break;
      case 5:
        hash = (37 * hash) + TIMESTAMPS_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamps().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.tika.grpc.v2.MetadataValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.MetadataValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.MetadataValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.MetadataValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.MetadataValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.MetadataValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.MetadataValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.MetadataValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.apache.tika.grpc.v2.MetadataValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.apache.tika.grpc.v2.MetadataValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.MetadataValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.MetadataValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.tika.grpc.v2.MetadataValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.apache.tika.grpc.v2.MetadataValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.apache.tika.grpc.v2.MetadataValue)
      org.apache.tika.grpc.v2.MetadataValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_MetadataValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_MetadataValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.tika.grpc.v2.MetadataValue.class, org.apache.tika.grpc.v2.MetadataValue.Builder.class);
    }

    // Construct using org.apache.tika.grpc.v2.MetadataValue.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (stringsBuilder_ != null) {
        stringsBuilder_.clear();
      }
      if (integersBuilder_ != null) {
        integersBuilder_.clear();
      }
      if (numbersBuilder_ != null) {
        numbersBuilder_.clear();
      }
      if (booleansBuilder_ != null) {
        booleansBuilder_.clear();
      }
      if (timestampsBuilder_ != null) {
        timestampsBuilder_.clear();
      }
      valuesCase_ = 0;
      values_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_MetadataValue_descriptor;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.MetadataValue getDefaultInstanceForType() {
      return org.apache.tika.grpc.v2.MetadataValue.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.MetadataValue build() {
      org.apache.tika.grpc.v2.MetadataValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.MetadataValue buildPartial() {
      org.apache.tika.grpc.v2.MetadataValue result = new org.apache.tika.grpc.v2.MetadataValue(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.tika.grpc.v2.MetadataValue result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(org.apache.tika.grpc.v2.MetadataValue result) {
      result.valuesCase_ = valuesCase_;
      result.values_ = this.values_;
      if (valuesCase_ == 1 &&
          stringsBuilder_ != null) {
        result.values_ = stringsBuilder_.build();
      }
      if (valuesCase_ == 2 &&
          integersBuilder_ != null) {
        result.values_ = integersBuilder_.build();
      }
      if (valuesCase_ == 3 &&
          numbersBuilder_ != null) {
        result.values_ = numbersBuilder_.build();
      }
      if (valuesCase_ == 4 &&
          booleansBuilder_ != null) {
        result.values_ = booleansBuilder_.build();
      }
      if (valuesCase_ == 5 &&
          timestampsBuilder_ != null) {
        result.values_ = timestampsBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.tika.grpc.v2.MetadataValue) {
        return mergeFrom((org.apache.tika.grpc.v2.MetadataValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.tika.grpc.v2.MetadataValue other) {
      if (other == org.apache.tika.grpc.v2.MetadataValue.getDefaultInstance()) return this;
      switch (other.getValuesCase()) {
        case STRINGS: {
          mergeStrings(other.getStrings());
          break;
        }
        case INTEGERS: {
          mergeIntegers(other.getIntegers());
          break;
        }
        case NUMBERS: {
          mergeNumbers(other.getNumbers());
          break;
        }
        case BOOLEANS: {
          mergeBooleans(other.getBooleans());
          break;
        }
        case TIMESTAMPS: {
          mergeTimestamps(other.getTimestamps());
          break;
        }
        case VALUES_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getStringsFieldBuilder().getBuilder(),
                  extensionRegistry);
              valuesCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getIntegersFieldBuilder().getBuilder(),
                  extensionRegistry);
              valuesCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getNumbersFieldBuilder().getBuilder(),
                  extensionRegistry);
              valuesCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getBooleansFieldBuilder().getBuilder(),
                  extensionRegistry);
              valuesCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getTimestampsFieldBuilder().getBuilder(),
                  extensionRegistry);
              valuesCase_ = 5;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int valuesCase_ = 0;
    private java.lang.Object values_;
    public ValuesCase
        getValuesCase() {
      return ValuesCase.forNumber(
          valuesCase_);
    }

    public Builder clearValues() {
      valuesCase_ = 0;
      values_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.StringValues, org.apache.tika.grpc.v2.StringValues.Builder, org.apache.tika.grpc.v2.StringValuesOrBuilder> stringsBuilder_;
    /**
     * <pre>
     * keys without a declared type
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
     * @return Whether the strings field is set.
     */
    @java.lang.Override
    public boolean hasStrings() {
      return valuesCase_ == 1;
    }
    /**
     * <pre>
     * keys without a declared type
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
     * @return The strings.
     */
    @java.lang.Override
    public org.apache.tika.grpc.v2.StringValues getStrings() {
      if (stringsBuilder_ == null) {
        if (valuesCase_ == 1) {
          return (org.apache.tika.grpc.v2.StringValues) values_;
        }
        return org.apache.tika.grpc.v2.StringValues.getDefaultInstance();
      } else {
        if (valuesCase_ == 1) {
          return stringsBuilder_.getMessage();
        }
        return org.apache.tika.grpc.v2.StringValues.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * keys without a declared type
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
     */
    public Builder setStrings(org.apache.tika.grpc.v2.StringValues value) {
      if (stringsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        values_ = value;
        onChanged();
      } else {
        stringsBuilder_.setMessage(value);
      }
      valuesCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * keys without a declared type
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
     */
    public Builder setStrings(
        org.apache.tika.grpc.v2.StringValues.Builder builderForValue) {
      if (stringsBuilder_ == null) {
        values_ = builderForValue.build();
        onChanged();
      } else {
        stringsBuilder_.setMessage(builderForValue.build());
      }
      valuesCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * keys without a declared type
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
     */
    public Builder mergeStrings(org.apache.tika.grpc.v2.StringValues value) {
      if (stringsBuilder_ == null) {
        if (valuesCase_ == 1 &&
            values_ != org.apache.tika.grpc.v2.StringValues.getDefaultInstance()) {
          values_ = org.apache.tika.grpc.v2.StringValues.newBuilder((org.apache.tika.grpc.v2.StringValues) values_)
              .mergeFrom(value).buildPartial();
        } else {
          values_ = value;
        }
        onChanged();
      } else {
        if (valuesCase_ == 1) {
          stringsBuilder_.mergeFrom(value);
        } else {
          stringsBuilder_.setMessage(value);
        }
      }
      valuesCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * keys without a declared type
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
     */
    public Builder clearStrings() {
      if (stringsBuilder_ == null) {
        if (valuesCase_ == 1) {
          valuesCase_ = 0;
          values_ = null;
          onChanged();
        }
      } else {
        if (valuesCase_ == 1) {
          valuesCase_ = 0;
          values_ = null;
        }
        stringsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * keys without a declared type
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
     */
    public org.apache.tika.grpc.v2.StringValues.Builder getStringsBuilder() {
      return getStringsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * keys without a declared type
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
     */
    @java.lang.Override
    public org.apache.tika.grpc.v2.StringValuesOrBuilder getStringsOrBuilder() {
      if ((valuesCase_ == 1) && (stringsBuilder_ != null)) {
        return stringsBuilder_.getMessageOrBuilder();
      } else {
        if (valuesCase_ == 1) {
          return (org.apache.tika.grpc.v2.StringValues) values_;
        }
        return org.apache.tika.grpc.v2.StringValues.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * keys without a declared type
     * </pre>
     *
     * <code>.org.apache.tika.grpc.v2.StringValues strings = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.StringValues, org.apache.tika.grpc.v2.StringValues.Builder, org.apache.tika.grpc.v2.StringValuesOrBuilder> 
        getStringsFieldBuilder() {
      if (stringsBuilder_ == null) {
        if (!(valuesCase_ == 1)) {
          values_ = org.apache.tika.grpc.v2.StringValues.getDefaultInstance();
        }
        stringsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.tika.grpc.v2.StringValues, org.apache.tika.grpc.v2.StringValues.Builder, org.apache.tika.grpc.v2.StringValuesOrBuilder>(
                (org.apache.tika.grpc.v2.StringValues) values_,
                getParentForChildren(),
                isClean());
        values_ = null;
      }
      valuesCase_ = 1;
      onChanged();
      return stringsBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.IntegerValues, org.apache.tika.grpc.v2.IntegerValues.Builder, org.apache.tika.grpc.v2.IntegerValuesOrBuilder> integersBuilder_;
    /**
     * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
     * @return Whether the integers field is set.
     */
    @java.lang.Override
    public boolean hasIntegers() {
      return valuesCase_ == 2;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
     * @return The integers.
     */
    @java.lang.Override
    public org.apache.tika.grpc.v2.IntegerValues getIntegers() {
      if (integersBuilder_ == null) {
        if (valuesCase_ == 2) {
          return (org.apache.tika.grpc.v2.IntegerValues) values_;
        }
        return org.apache.tika.grpc.v2.IntegerValues.getDefaultInstance();
      } else {
        if (valuesCase_ == 2) {
          return integersBuilder_.getMessage();
        }
        return org.apache.tika.grpc.v2.IntegerValues.getDefaultInstance();
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
     */
    public Builder setIntegers(org.apache.tika.grpc.v2.IntegerValues value) {
      if (integersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        values_ = value;
        onChanged();
      } else {
        integersBuilder_.setMessage(value);
      }
      valuesCase_ = 2;
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
     */
    public Builder setIntegers(
        org.apache.tika.grpc.v2.IntegerValues.Builder builderForValue) {
      if (integersBuilder_ == null) {
        values_ = builderForValue.build();
        onChanged();
      } else {
        integersBuilder_.setMessage(builderForValue.build());
      }
      valuesCase_ = 2;
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
     */
    public Builder mergeIntegers(org.apache.tika.grpc.v2.IntegerValues value) {
      if (integersBuilder_ == null) {
        if (valuesCase_ == 2 &&
            values_ != org.apache.tika.grpc.v2.IntegerValues.getDefaultInstance()) {
          values_ = org.apache.tika.grpc.v2.IntegerValues.newBuilder((org.apache.tika.grpc.v2.IntegerValues) values_)
              .mergeFrom(value).buildPartial();
        } else {
          values_ = value;
        }
        onChanged();
      } else {
        if (valuesCase_ == 2) {
          integersBuilder_.mergeFrom(value);
        } else {
          integersBuilder_.setMessage(value);
        }
      }
      valuesCase_ = 2;
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
     */
    public Builder clearIntegers() {
      if (integersBuilder_ == null) {
        if (valuesCase_ == 2) {
          valuesCase_ = 0;
          values_ = null;
          onChanged();
        }
      } else {
        if (valuesCase_ == 2) {
          valuesCase_ = 0;
          values_ = null;
        }
        integersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
     */
    public org.apache.tika.grpc.v2.IntegerValues.Builder getIntegersBuilder() {
      return getIntegersFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
     */
    @java.lang.Override
    public org.apache.tika.grpc.v2.IntegerValuesOrBuilder getIntegersOrBuilder() {
      if ((valuesCase_ == 2) && (integersBuilder_ != null)) {
        return integersBuilder_.getMessageOrBuilder();
      } else {
        if (valuesCase_ == 2) {
          return (org.apache.tika.grpc.v2.IntegerValues) values_;
        }
        return org.apache.tika.grpc.v2.IntegerValues.getDefaultInstance();
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.IntegerValues integers = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.IntegerValues, org.apache.tika.grpc.v2.IntegerValues.Builder, org.apache.tika.grpc.v2.IntegerValuesOrBuilder> 
        getIntegersFieldBuilder() {
      if (integersBuilder_ == null) {
        if (!(valuesCase_ == 2)) {
          values_ = org.apache.tika.grpc.v2.IntegerValues.getDefaultInstance();
        }
        integersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.tika.grpc.v2.IntegerValues, org.apache.tika.grpc.v2.IntegerValues.Builder, org.apache.tika.grpc.v2.IntegerValuesOrBuilder>(
                (org.apache.tika.grpc.v2.IntegerValues) values_,
                getParentForChildren(),
                isClean());
        values_ = null;
      }
      valuesCase_ = 2;
      onChanged();
      return integersBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.NumberValues, org.apache.tika.grpc.v2.NumberValues.Builder, org.apache.tika.grpc.v2.NumberValuesOrBuilder> numbersBuilder_;
    /**
     * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
     * @return Whether the numbers field is set.
     */
    @java.lang.Override
    public boolean hasNumbers() {
      return valuesCase_ == 3;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
     * @return The numbers.
     */
    @java.lang.Override
    public org.apache.tika.grpc.v2.NumberValues getNumbers() {
      if (numbersBuilder_ == null) {
        if (valuesCase_ == 3) {
          return (org.apache.tika.grpc.v2.NumberValues) values_;
        }
        return org.apache.tika.grpc.v2.NumberValues.getDefaultInstance();
      } else {
        if (valuesCase_ == 3) {
          return numbersBuilder_.getMessage();
        }
        return org.apache.tika.grpc.v2.NumberValues.getDefaultInstance();
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
     */
    public Builder setNumbers(org.apache.tika.grpc.v2.NumberValues value) {
      if (numbersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        values_ = value;
        onChanged();
      } else {
        numbersBuilder_.setMessage(value);
      }
      valuesCase_ = 3;
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
     */
    public Builder setNumbers(
        org.apache.tika.grpc.v2.NumberValues.Builder builderForValue) {
      if (numbersBuilder_ == null) {
        values_ = builderForValue.build();
        onChanged();
      } else {
        numbersBuilder_.setMessage(builderForValue.build());
      }
      valuesCase_ = 3;
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
     */
    public Builder mergeNumbers(org.apache.tika.grpc.v2.NumberValues value) {
      if (numbersBuilder_ == null) {
        if (valuesCase_ == 3 &&
            values_ != org.apache.tika.grpc.v2.NumberValues.getDefaultInstance()) {
          values_ = org.apache.tika.grpc.v2.NumberValues.newBuilder((org.apache.tika.grpc.v2.NumberValues) values_)
              .mergeFrom(value).buildPartial();
        } else {
          values_ = value;
        }
        onChanged();
      } else {
        if (valuesCase_ == 3) {
          numbersBuilder_.mergeFrom(value);
        } else {
          numbersBuilder_.setMessage(value);
        }
      }
      valuesCase_ = 3;
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
     */
    public Builder clearNumbers() {
      if (numbersBuilder_ == null) {
        if (valuesCase_ == 3) {
          valuesCase_ = 0;
          values_ = null;
          onChanged();
        }
      } else {
        if (valuesCase_ == 3) {
          valuesCase_ = 0;
          values_ = null;
        }
        numbersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
     */
    public org.apache.tika.grpc.v2.NumberValues.Builder getNumbersBuilder() {
      return getNumbersFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
     */
    @java.lang.Override
    public org.apache.tika.grpc.v2.NumberValuesOrBuilder getNumbersOrBuilder() {
      if ((valuesCase_ == 3) && (numbersBuilder_ != null)) {
        return numbersBuilder_.getMessageOrBuilder();
      } else {
        if (valuesCase_ == 3) {
          return (org.apache.tika.grpc.v2.NumberValues) values_;
        }
        return org.apache.tika.grpc.v2.NumberValues.getDefaultInstance();
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.NumberValues numbers = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.NumberValues, org.apache.tika.grpc.v2.NumberValues.Builder, org.apache.tika.grpc.v2.NumberValuesOrBuilder> 
        getNumbersFieldBuilder() {
      if (numbersBuilder_ == null) {
        if (!(valuesCase_ == 3)) {
          values_ = org.apache.tika.grpc.v2.NumberValues.getDefaultInstance();
        }
        numbersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.tika.grpc.v2.NumberValues, org.apache.tika.grpc.v2.NumberValues.Builder, org.apache.tika.grpc.v2.NumberValuesOrBuilder>(
                (org.apache.tika.grpc.v2.NumberValues) values_,
                getParentForChildren(),
                isClean());
        values_ = null;
      }
      valuesCase_ = 3;
      onChanged();
      return numbersBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.BooleanValues, org.apache.tika.grpc.v2.BooleanValues.Builder, org.apache.tika.grpc.v2.BooleanValuesOrBuilder> booleansBuilder_;
    /**
     * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
     * @return Whether the booleans field is set.
     */
    @java.lang.Override
    public boolean hasBooleans() {
      return valuesCase_ == 4;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
     * @return The booleans.
     */
    @java.lang.Override
    public org.apache.tika.grpc.v2.BooleanValues getBooleans() {
      if (booleansBuilder_ == null) {
        if (valuesCase_ == 4) {
          return (org.apache.tika.grpc.v2.BooleanValues) values_;
        }
        return org.apache.tika.grpc.v2.BooleanValues.getDefaultInstance();
      } else {
        if (valuesCase_ == 4) {
          return booleansBuilder_.getMessage();
        }
        return org.apache.tika.grpc.v2.BooleanValues.getDefaultInstance();
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
     */
    public Builder setBooleans(org.apache.tika.grpc.v2.BooleanValues value) {
      if (booleansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        values_ = value;
        onChanged();
      } else {
        booleansBuilder_.setMessage(value);
      }
      valuesCase_ = 4;
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
     */
    public Builder setBooleans(
        org.apache.tika.grpc.v2.BooleanValues.Builder builderForValue) {
      if (booleansBuilder_ == null) {
        values_ = builderForValue.build();
        onChanged();
      } else {
        booleansBuilder_.setMessage(builderForValue.build());
      }
      valuesCase_ = 4;
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
     */
    public Builder mergeBooleans(org.apache.tika.grpc.v2.BooleanValues value) {
      if (booleansBuilder_ == null) {
        if (valuesCase_ == 4 &&
            values_ != org.apache.tika.grpc.v2.BooleanValues.getDefaultInstance()) {
          values_ = org.apache.tika.grpc.v2.BooleanValues.newBuilder((org.apache.tika.grpc.v2.BooleanValues) values_)
              .mergeFrom(value).buildPartial();
        } else {
          values_ = value;
        }
        onChanged();
      } else {
        if (valuesCase_ == 4) {
          booleansBuilder_.mergeFrom(value);
        } else {
          booleansBuilder_.setMessage(value);
        }
      }
      valuesCase_ = 4;
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
     */
    public Builder clearBooleans() {
      if (booleansBuilder_ == null) {
        if (valuesCase_ == 4) {
          valuesCase_ = 0;
          values_ = null;
          onChanged();
        }
      } else {
        if (valuesCase_ == 4) {
          valuesCase_ = 0;
          values_ = null;
        }
        booleansBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
     */
    public org.apache.tika.grpc.v2.BooleanValues.Builder getBooleansBuilder() {
      return getBooleansFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
     */
    @java.lang.Override
    public org.apache.tika.grpc.v2.BooleanValuesOrBuilder getBooleansOrBuilder() {
      if ((valuesCase_ == 4) && (booleansBuilder_ != null)) {
        return booleansBuilder_.getMessageOrBuilder();
      } else {
        if (valuesCase_ == 4) {
          return (org.apache.tika.grpc.v2.BooleanValues) values_;
        }
        return org.apache.tika.grpc.v2.BooleanValues.getDefaultInstance();
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.BooleanValues booleans = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.BooleanValues, org.apache.tika.grpc.v2.BooleanValues.Builder, org.apache.tika.grpc.v2.BooleanValuesOrBuilder> 
        getBooleansFieldBuilder() {
      if (booleansBuilder_ == null) {
        if (!(valuesCase_ == 4)) {
          values_ = org.apache.tika.grpc.v2.BooleanValues.getDefaultInstance();
        }
        booleansBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.tika.grpc.v2.BooleanValues, org.apache.tika.grpc.v2.BooleanValues.Builder, org.apache.tika.grpc.v2.BooleanValuesOrBuilder>(
                (org.apache.tika.grpc.v2.BooleanValues) values_,
                getParentForChildren(),
                isClean());
        values_ = null;
      }
      valuesCase_ = 4;
      onChanged();
      return booleansBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.TimestampValues, org.apache.tika.grpc.v2.TimestampValues.Builder, org.apache.tika.grpc.v2.TimestampValuesOrBuilder> timestampsBuilder_;
    /**
     * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
     * @return Whether the timestamps field is set.
     */
    @java.lang.Override
    public boolean hasTimestamps() {
      return valuesCase_ == 5;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
     * @return The timestamps.
     */
    @java.lang.Override
    public org.apache.tika.grpc.v2.TimestampValues getTimestamps() {
      if (timestampsBuilder_ == null) {
        if (valuesCase_ == 5) {
          return (org.apache.tika.grpc.v2.TimestampValues) values_;
        }
        return org.apache.tika.grpc.v2.TimestampValues.getDefaultInstance();
      } else {
        if (valuesCase_ == 5) {
          return timestampsBuilder_.getMessage();
        }
        return org.apache.tika.grpc.v2.TimestampValues.getDefaultInstance();
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
     */
    public Builder setTimestamps(org.apache.tika.grpc.v2.TimestampValues value) {
      if (timestampsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        values_ = value;
        onChanged();
      } else {
        timestampsBuilder_.setMessage(value);
      }
      valuesCase_ = 5;
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
     */
    public Builder setTimestamps(
        org.apache.tika.grpc.v2.TimestampValues.Builder builderForValue) {
      if (timestampsBuilder_ == null) {
        values_ = builderForValue.build();
        onChanged();
      } else {
        timestampsBuilder_.setMessage(builderForValue.build());
      }
      valuesCase_ = 5;
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
     */
    public Builder mergeTimestamps(org.apache.tika.grpc.v2.TimestampValues value) {
      if (timestampsBuilder_ == null) {
        if (valuesCase_ == 5 &&
            values_ != org.apache.tika.grpc.v2.TimestampValues.getDefaultInstance()) {
          values_ = org.apache.tika.grpc.v2.TimestampValues.newBuilder((org.apache.tika.grpc.v2.TimestampValues) values_)
              .mergeFrom(value).buildPartial();
        } else {
          values_ = value;
        }
        onChanged();
      } else {
        if (valuesCase_ == 5) {
          timestampsBuilder_.mergeFrom(value);
        } else {
          timestampsBuilder_.setMessage(value);
        }
      }
      valuesCase_ = 5;
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
     */
    public Builder clearTimestamps() {
      if (timestampsBuilder_ == null) {
        if (valuesCase_ == 5) {
          valuesCase_ = 0;
          values_ = null;
          onChanged();
        }
      } else {
        if (valuesCase_ == 5) {
          valuesCase_ = 0;
          values_ = null;
        }
        timestampsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
     */
    public org.apache.tika.grpc.v2.TimestampValues.Builder getTimestampsBuilder() {
      return getTimestampsFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
     */
    @java.lang.Override
    public org.apache.tika.grpc.v2.TimestampValuesOrBuilder getTimestampsOrBuilder() {
      if ((valuesCase_ == 5) && (timestampsBuilder_ != null)) {
        return timestampsBuilder_.getMessageOrBuilder();
      } else {
        if (valuesCase_ == 5) {
          return (org.apache.tika.grpc.v2.TimestampValues) values_;
        }
        return org.apache.tika.grpc.v2.TimestampValues.getDefaultInstance();
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.TimestampValues timestamps = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.TimestampValues, org.apache.tika.grpc.v2.TimestampValues.Builder, org.apache.tika.grpc.v2.TimestampValuesOrBuilder> 
        getTimestampsFieldBuilder() {
      if (timestampsBuilder_ == null) {
        if (!(valuesCase_ == 5)) {
          values_ = org.apache.tika.grpc.v2.TimestampValues.getDefaultInstance();
        }
        timestampsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.tika.grpc.v2.TimestampValues, org.apache.tika.grpc.v2.TimestampValues.Builder, org.apache.tika.grpc.v2.TimestampValuesOrBuilder>(
                (org.apache.tika.grpc.v2.TimestampValues) values_,
                getParentForChildren(),
                isClean());
        values_ = null;
      }
      valuesCase_ = 5;
      onChanged();
      return timestampsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.apache.tika.grpc.v2.MetadataValue)
  }

  // @@protoc_insertion_point(class_scope:org.apache.tika.grpc.v2.MetadataValue)
  private static final org.apache.tika.grpc.v2.MetadataValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.tika.grpc.v2.MetadataValue();
  }

  public static org.apache.tika.grpc.v2.MetadataValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetadataValue>
      PARSER = new com.google.protobuf.AbstractParser<MetadataValue>() {
    @java.lang.Override
    public MetadataValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MetadataValue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetadataValue> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.tika.grpc.v2.MetadataValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

