// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/tika_v2.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

public interface ParseBytesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.tika.grpc.v2.ParseBytesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The caller's id for this request, returned unchanged as Document.id and
   * ParseBytesReply.correlation_id.
   * </pre>
   *
   * <code>string correlation_id = 1;</code>
   * @return The correlationId.
   */
  java.lang.String getCorrelationId();
  /**
   * <pre>
   * The caller's id for this request, returned unchanged as Document.id and
   * ParseBytesReply.correlation_id.
   * </pre>
   *
   * <code>string correlation_id = 1;</code>
   * @return The bytes for correlationId.
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();

  /**
   * <pre>
   * Bytes to parse. Required, at most the server's parseBytesMaxContentBytes. The
   * whole request must also fit the server's gRPC inbound limit: 4 MiB unless
   * maxInboundMessageBytes sets another value.
   * </pre>
   *
   * <code>bytes content = 2;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <pre>
   * Optional file name, such as "page.html". Tika uses it to detect the content type
   * and returns it as Document.origin.filename.
   * </pre>
   *
   * <code>string resource_name = 3;</code>
   * @return The resourceName.
   */
  java.lang.String getResourceName();
  /**
   * <pre>
   * Optional file name, such as "page.html". Tika uses it to detect the content type
   * and returns it as Document.origin.filename.
   * </pre>
   *
   * <code>string resource_name = 3;</code>
   * @return The bytes for resourceName.
   */
  com.google.protobuf.ByteString
      getResourceNameBytes();

  /**
   * <pre>
   * Optional URIs the caller records for the bytes, such as the requested URL, the
   * URL after redirects and the base URL for relative links. Tika returns them in
   * Document.origin and does not use them.
   * </pre>
   *
   * <code>string source_uri = 4;</code>
   * @return The sourceUri.
   */
  java.lang.String getSourceUri();
  /**
   * <pre>
   * Optional URIs the caller records for the bytes, such as the requested URL, the
   * URL after redirects and the base URL for relative links. Tika returns them in
   * Document.origin and does not use them.
   * </pre>
   *
   * <code>string source_uri = 4;</code>
   * @return The bytes for sourceUri.
   */
  com.google.protobuf.ByteString
      getSourceUriBytes();

  /**
   * <code>string effective_uri = 5;</code>
   * @return The effectiveUri.
   */
  java.lang.String getEffectiveUri();
  /**
   * <code>string effective_uri = 5;</code>
   * @return The bytes for effectiveUri.
   */
  com.google.protobuf.ByteString
      getEffectiveUriBytes();

  /**
   * <code>string base_uri = 6;</code>
   * @return The baseUri.
   */
  java.lang.String getBaseUri();
  /**
   * <code>string base_uri = 6;</code>
   * @return The bytes for baseUri.
   */
  com.google.protobuf.ByteString
      getBaseUriBytes();

  /**
   * <pre>
   * Set when the caller cut the bytes short, for example at a crawler's size limit.
   * Returned as Document.origin.truncated.
   * </pre>
   *
   * <code>bool truncated = 7;</code>
   * @return The truncated.
   */
  boolean getTruncated();

  /**
   * <pre>
   * Optional JSON object to configure the ParseContext for this request.
   * </pre>
   *
   * <code>string parse_context_json = 8;</code>
   * @return The parseContextJson.
   */
  java.lang.String getParseContextJson();
  /**
   * <pre>
   * Optional JSON object to configure the ParseContext for this request.
   * </pre>
   *
   * <code>string parse_context_json = 8;</code>
   * @return The bytes for parseContextJson.
   */
  com.google.protobuf.ByteString
      getParseContextJsonBytes();
}
