// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/document.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

/**
 * Protobuf type {@code org.apache.tika.grpc.v2.ParseStatus}
 */
public final class ParseStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.apache.tika.grpc.v2.ParseStatus)
    ParseStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ParseStatus.newBuilder() to construct.
  private ParseStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ParseStatus() {
    status_ = 0;
    parsersUsed_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    errors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    tikaVersion_ = "";
    pipesStatus_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ParseStatus();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_ParseStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_ParseStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.tika.grpc.v2.ParseStatus.class, org.apache.tika.grpc.v2.ParseStatus.Builder.class);
  }

  /**
   * Protobuf enum {@code org.apache.tika.grpc.v2.ParseStatus.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNSPECIFIED = 0;</code>
     */
    UNSPECIFIED(0),
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(1),
    /**
     * <code>PARTIAL = 2;</code>
     */
    PARTIAL(2),
    /**
     * <code>FAILED = 3;</code>
     */
    FAILED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNSPECIFIED = 0;</code>
     */
    public static final int UNSPECIFIED_VALUE = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;
    /**
     * <code>PARTIAL = 2;</code>
     */
    public static final int PARTIAL_VALUE = 2;
    /**
     * <code>FAILED = 3;</code>
     */
    public static final int FAILED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Status forNumber(int value) {
      switch (value) {
        case 0: return UNSPECIFIED;
        case 1: return SUCCESS;
        case 2: return PARTIAL;
        case 3: return FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.apache.tika.grpc.v2.ParseStatus.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.apache.tika.grpc.v2.ParseStatus.Status)
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_ = 0;
  /**
   * <code>.org.apache.tika.grpc.v2.ParseStatus.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.org.apache.tika.grpc.v2.ParseStatus.Status status = 1;</code>
   * @return The status.
   */
  @java.lang.Override public org.apache.tika.grpc.v2.ParseStatus.Status getStatus() {
    org.apache.tika.grpc.v2.ParseStatus.Status result = org.apache.tika.grpc.v2.ParseStatus.Status.forNumber(status_);
    return result == null ? org.apache.tika.grpc.v2.ParseStatus.Status.UNRECOGNIZED : result;
  }

  public static final int FETCH_PARSE_TIME_MS_FIELD_NUMBER = 2;
  private long fetchParseTimeMs_ = 0L;
  /**
   * <pre>
   * Milliseconds for the whole fetch and parse, measured by the server. Both happen
   * in the forked pipes worker, so the parse time alone is not available.
   * </pre>
   *
   * <code>int64 fetch_parse_time_ms = 2;</code>
   * @return The fetchParseTimeMs.
   */
  @java.lang.Override
  public long getFetchParseTimeMs() {
    return fetchParseTimeMs_;
  }

  public static final int PARSERS_USED_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList parsersUsed_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string parsers_used = 3;</code>
   * @return A list containing the parsersUsed.
   */
  public com.google.protobuf.ProtocolStringList
      getParsersUsedList() {
    return parsersUsed_;
  }
  /**
   * <code>repeated string parsers_used = 3;</code>
   * @return The count of parsersUsed.
   */
  public int getParsersUsedCount() {
    return parsersUsed_.size();
  }
  /**
   * <code>repeated string parsers_used = 3;</code>
   * @param index The index of the element to return.
   * @return The parsersUsed at the given index.
   */
  public java.lang.String getParsersUsed(int index) {
    return parsersUsed_.get(index);
  }
  /**
   * <code>repeated string parsers_used = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the parsersUsed at the given index.
   */
  public com.google.protobuf.ByteString
      getParsersUsedBytes(int index) {
    return parsersUsed_.getByteString(index);
  }

  public static final int ERRORS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList errors_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string errors = 4;</code>
   * @return A list containing the errors.
   */
  public com.google.protobuf.ProtocolStringList
      getErrorsList() {
    return errors_;
  }
  /**
   * <code>repeated string errors = 4;</code>
   * @return The count of errors.
   */
  public int getErrorsCount() {
    return errors_.size();
  }
  /**
   * <code>repeated string errors = 4;</code>
   * @param index The index of the element to return.
   * @return The errors at the given index.
   */
  public java.lang.String getErrors(int index) {
    return errors_.get(index);
  }
  /**
   * <code>repeated string errors = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the errors at the given index.
   */
  public com.google.protobuf.ByteString
      getErrorsBytes(int index) {
    return errors_.getByteString(index);
  }

  public static final int TIKA_VERSION_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tikaVersion_ = "";
  /**
   * <pre>
   * Version string of the Tika that produced this document (e.g. "Apache Tika 4.0.0"),
   * so long-lived stores can tell which producer wrote an entry.
   * </pre>
   *
   * <code>string tika_version = 5;</code>
   * @return The tikaVersion.
   */
  @java.lang.Override
  public java.lang.String getTikaVersion() {
    java.lang.Object ref = tikaVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tikaVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Version string of the Tika that produced this document (e.g. "Apache Tika 4.0.0"),
   * so long-lived stores can tell which producer wrote an entry.
   * </pre>
   *
   * <code>string tika_version = 5;</code>
   * @return The bytes for tikaVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTikaVersionBytes() {
    java.lang.Object ref = tikaVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tikaVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PIPES_STATUS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pipesStatus_ = "";
  /**
   * <pre>
   * The raw pipes result `status` was derived from (e.g. "PARSE_SUCCESS", "TIMEOUT";
   * see org.apache.tika.pipes.api.PipesResult.RESULT_STATUS). Its values can change
   * between Tika versions: branch on `status` and use this for logs.
   * </pre>
   *
   * <code>string pipes_status = 6;</code>
   * @return The pipesStatus.
   */
  @java.lang.Override
  public java.lang.String getPipesStatus() {
    java.lang.Object ref = pipesStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pipesStatus_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The raw pipes result `status` was derived from (e.g. "PARSE_SUCCESS", "TIMEOUT";
   * see org.apache.tika.pipes.api.PipesResult.RESULT_STATUS). Its values can change
   * between Tika versions: branch on `status` and use this for logs.
   * </pre>
   *
   * <code>string pipes_status = 6;</code>
   * @return The bytes for pipesStatus.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPipesStatusBytes() {
    java.lang.Object ref = pipesStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pipesStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != org.apache.tika.grpc.v2.ParseStatus.Status.UNSPECIFIED.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (fetchParseTimeMs_ != 0L) {
      output.writeInt64(2, fetchParseTimeMs_);
    }
    for (int i = 0; i < parsersUsed_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, parsersUsed_.getRaw(i));
    }
    for (int i = 0; i < errors_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, errors_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tikaVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tikaVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pipesStatus_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, pipesStatus_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != org.apache.tika.grpc.v2.ParseStatus.Status.UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (fetchParseTimeMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, fetchParseTimeMs_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < parsersUsed_.size(); i++) {
        dataSize += computeStringSizeNoTag(parsersUsed_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getParsersUsedList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < errors_.size(); i++) {
        dataSize += computeStringSizeNoTag(errors_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getErrorsList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tikaVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tikaVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pipesStatus_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, pipesStatus_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.tika.grpc.v2.ParseStatus)) {
      return super.equals(obj);
    }
    org.apache.tika.grpc.v2.ParseStatus other = (org.apache.tika.grpc.v2.ParseStatus) obj;

    if (status_ != other.status_) return false;
    if (getFetchParseTimeMs()
        != other.getFetchParseTimeMs()) return false;
    if (!getParsersUsedList()
        .equals(other.getParsersUsedList())) return false;
    if (!getErrorsList()
        .equals(other.getErrorsList())) return false;
    if (!getTikaVersion()
        .equals(other.getTikaVersion())) return false;
    if (!getPipesStatus()
        .equals(other.getPipesStatus())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + FETCH_PARSE_TIME_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFetchParseTimeMs());
    if (getParsersUsedCount() > 0) {
      hash = (37 * hash) + PARSERS_USED_FIELD_NUMBER;
      hash = (53 * hash) + getParsersUsedList().hashCode();
    }
    if (getErrorsCount() > 0) {
      hash = (37 * hash) + ERRORS_FIELD_NUMBER;
      hash = (53 * hash) + getErrorsList().hashCode();
    }
    hash = (37 * hash) + TIKA_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getTikaVersion().hashCode();
    hash = (37 * hash) + PIPES_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getPipesStatus().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.tika.grpc.v2.ParseStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.ParseStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.ParseStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.ParseStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.ParseStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.ParseStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.ParseStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.ParseStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.apache.tika.grpc.v2.ParseStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.apache.tika.grpc.v2.ParseStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.ParseStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.ParseStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.tika.grpc.v2.ParseStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.apache.tika.grpc.v2.ParseStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.apache.tika.grpc.v2.ParseStatus)
      org.apache.tika.grpc.v2.ParseStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_ParseStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_ParseStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.tika.grpc.v2.ParseStatus.class, org.apache.tika.grpc.v2.ParseStatus.Builder.class);
    }

    // Construct using org.apache.tika.grpc.v2.ParseStatus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = 0;
      fetchParseTimeMs_ = 0L;
      parsersUsed_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      errors_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      tikaVersion_ = "";
      pipesStatus_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_ParseStatus_descriptor;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.ParseStatus getDefaultInstanceForType() {
      return org.apache.tika.grpc.v2.ParseStatus.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.ParseStatus build() {
      org.apache.tika.grpc.v2.ParseStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.ParseStatus buildPartial() {
      org.apache.tika.grpc.v2.ParseStatus result = new org.apache.tika.grpc.v2.ParseStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.tika.grpc.v2.ParseStatus result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fetchParseTimeMs_ = fetchParseTimeMs_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        parsersUsed_.makeImmutable();
        result.parsersUsed_ = parsersUsed_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        errors_.makeImmutable();
        result.errors_ = errors_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.tikaVersion_ = tikaVersion_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.pipesStatus_ = pipesStatus_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.tika.grpc.v2.ParseStatus) {
        return mergeFrom((org.apache.tika.grpc.v2.ParseStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.tika.grpc.v2.ParseStatus other) {
      if (other == org.apache.tika.grpc.v2.ParseStatus.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getFetchParseTimeMs() != 0L) {
        setFetchParseTimeMs(other.getFetchParseTimeMs());
      }
      if (!other.parsersUsed_.isEmpty()) {
        if (parsersUsed_.isEmpty()) {
          parsersUsed_ = other.parsersUsed_;
          bitField0_ |= 0x00000004;
        } else {
          ensureParsersUsedIsMutable();
          parsersUsed_.addAll(other.parsersUsed_);
        }
        onChanged();
      }
      if (!other.errors_.isEmpty()) {
        if (errors_.isEmpty()) {
          errors_ = other.errors_;
          bitField0_ |= 0x00000008;
        } else {
          ensureErrorsIsMutable();
          errors_.addAll(other.errors_);
        }
        onChanged();
      }
      if (!other.getTikaVersion().isEmpty()) {
        tikaVersion_ = other.tikaVersion_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getPipesStatus().isEmpty()) {
        pipesStatus_ = other.pipesStatus_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              fetchParseTimeMs_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureParsersUsedIsMutable();
              parsersUsed_.add(s);
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureErrorsIsMutable();
              errors_.add(s);
              break;
            } // case 34
            case 42: {
              tikaVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              pipesStatus_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int status_ = 0;
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus.Status status = 1;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus.Status status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public org.apache.tika.grpc.v2.ParseStatus.Status getStatus() {
      org.apache.tika.grpc.v2.ParseStatus.Status result = org.apache.tika.grpc.v2.ParseStatus.Status.forNumber(status_);
      return result == null ? org.apache.tika.grpc.v2.ParseStatus.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus.Status status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(org.apache.tika.grpc.v2.ParseStatus.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.ParseStatus.Status status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
      onChanged();
      return this;
    }

    private long fetchParseTimeMs_ ;
    /**
     * <pre>
     * Milliseconds for the whole fetch and parse, measured by the server. Both happen
     * in the forked pipes worker, so the parse time alone is not available.
     * </pre>
     *
     * <code>int64 fetch_parse_time_ms = 2;</code>
     * @return The fetchParseTimeMs.
     */
    @java.lang.Override
    public long getFetchParseTimeMs() {
      return fetchParseTimeMs_;
    }
    /**
     * <pre>
     * Milliseconds for the whole fetch and parse, measured by the server. Both happen
     * in the forked pipes worker, so the parse time alone is not available.
     * </pre>
     *
     * <code>int64 fetch_parse_time_ms = 2;</code>
     * @param value The fetchParseTimeMs to set.
     * @return This builder for chaining.
     */
    public Builder setFetchParseTimeMs(long value) {

      fetchParseTimeMs_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Milliseconds for the whole fetch and parse, measured by the server. Both happen
     * in the forked pipes worker, so the parse time alone is not available.
     * </pre>
     *
     * <code>int64 fetch_parse_time_ms = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFetchParseTimeMs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      fetchParseTimeMs_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList parsersUsed_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureParsersUsedIsMutable() {
      if (!parsersUsed_.isModifiable()) {
        parsersUsed_ = new com.google.protobuf.LazyStringArrayList(parsersUsed_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string parsers_used = 3;</code>
     * @return A list containing the parsersUsed.
     */
    public com.google.protobuf.ProtocolStringList
        getParsersUsedList() {
      parsersUsed_.makeImmutable();
      return parsersUsed_;
    }
    /**
     * <code>repeated string parsers_used = 3;</code>
     * @return The count of parsersUsed.
     */
    public int getParsersUsedCount() {
      return parsersUsed_.size();
    }
    /**
     * <code>repeated string parsers_used = 3;</code>
     * @param index The index of the element to return.
     * @return The parsersUsed at the given index.
     */
    public java.lang.String getParsersUsed(int index) {
      return parsersUsed_.get(index);
    }
    /**
     * <code>repeated string parsers_used = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parsersUsed at the given index.
     */
    public com.google.protobuf.ByteString
        getParsersUsedBytes(int index) {
      return parsersUsed_.getByteString(index);
    }
    /**
     * <code>repeated string parsers_used = 3;</code>
     * @param index The index to set the value at.
     * @param value The parsersUsed to set.
     * @return This builder for chaining.
     */
    public Builder setParsersUsed(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureParsersUsedIsMutable();
      parsersUsed_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string parsers_used = 3;</code>
     * @param value The parsersUsed to add.
     * @return This builder for chaining.
     */
    public Builder addParsersUsed(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureParsersUsedIsMutable();
      parsersUsed_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string parsers_used = 3;</code>
     * @param values The parsersUsed to add.
     * @return This builder for chaining.
     */
    public Builder addAllParsersUsed(
        java.lang.Iterable<java.lang.String> values) {
      ensureParsersUsedIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, parsersUsed_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string parsers_used = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearParsersUsed() {
      parsersUsed_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string parsers_used = 3;</code>
     * @param value The bytes of the parsersUsed to add.
     * @return This builder for chaining.
     */
    public Builder addParsersUsedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureParsersUsedIsMutable();
      parsersUsed_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList errors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureErrorsIsMutable() {
      if (!errors_.isModifiable()) {
        errors_ = new com.google.protobuf.LazyStringArrayList(errors_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string errors = 4;</code>
     * @return A list containing the errors.
     */
    public com.google.protobuf.ProtocolStringList
        getErrorsList() {
      errors_.makeImmutable();
      return errors_;
    }
    /**
     * <code>repeated string errors = 4;</code>
     * @return The count of errors.
     */
    public int getErrorsCount() {
      return errors_.size();
    }
    /**
     * <code>repeated string errors = 4;</code>
     * @param index The index of the element to return.
     * @return The errors at the given index.
     */
    public java.lang.String getErrors(int index) {
      return errors_.get(index);
    }
    /**
     * <code>repeated string errors = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the errors at the given index.
     */
    public com.google.protobuf.ByteString
        getErrorsBytes(int index) {
      return errors_.getByteString(index);
    }
    /**
     * <code>repeated string errors = 4;</code>
     * @param index The index to set the value at.
     * @param value The errors to set.
     * @return This builder for chaining.
     */
    public Builder setErrors(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureErrorsIsMutable();
      errors_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string errors = 4;</code>
     * @param value The errors to add.
     * @return This builder for chaining.
     */
    public Builder addErrors(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureErrorsIsMutable();
      errors_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string errors = 4;</code>
     * @param values The errors to add.
     * @return This builder for chaining.
     */
    public Builder addAllErrors(
        java.lang.Iterable<java.lang.String> values) {
      ensureErrorsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, errors_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string errors = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrors() {
      errors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string errors = 4;</code>
     * @param value The bytes of the errors to add.
     * @return This builder for chaining.
     */
    public Builder addErrorsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureErrorsIsMutable();
      errors_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object tikaVersion_ = "";
    /**
     * <pre>
     * Version string of the Tika that produced this document (e.g. "Apache Tika 4.0.0"),
     * so long-lived stores can tell which producer wrote an entry.
     * </pre>
     *
     * <code>string tika_version = 5;</code>
     * @return The tikaVersion.
     */
    public java.lang.String getTikaVersion() {
      java.lang.Object ref = tikaVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tikaVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Version string of the Tika that produced this document (e.g. "Apache Tika 4.0.0"),
     * so long-lived stores can tell which producer wrote an entry.
     * </pre>
     *
     * <code>string tika_version = 5;</code>
     * @return The bytes for tikaVersion.
     */
    public com.google.protobuf.ByteString
        getTikaVersionBytes() {
      java.lang.Object ref = tikaVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tikaVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Version string of the Tika that produced this document (e.g. "Apache Tika 4.0.0"),
     * so long-lived stores can tell which producer wrote an entry.
     * </pre>
     *
     * <code>string tika_version = 5;</code>
     * @param value The tikaVersion to set.
     * @return This builder for chaining.
     */
    public Builder setTikaVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tikaVersion_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version string of the Tika that produced this document (e.g. "Apache Tika 4.0.0"),
     * so long-lived stores can tell which producer wrote an entry.
     * </pre>
     *
     * <code>string tika_version = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTikaVersion() {
      tikaVersion_ = getDefaultInstance().getTikaVersion();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version string of the Tika that produced this document (e.g. "Apache Tika 4.0.0"),
     * so long-lived stores can tell which producer wrote an entry.
     * </pre>
     *
     * <code>string tika_version = 5;</code>
     * @param value The bytes for tikaVersion to set.
     * @return This builder for chaining.
     */
    public Builder setTikaVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tikaVersion_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object pipesStatus_ = "";
    /**
     * <pre>
     * The raw pipes result `status` was derived from (e.g. "PARSE_SUCCESS", "TIMEOUT";
     * see org.apache.tika.pipes.api.PipesResult.RESULT_STATUS). Its values can change
     * between Tika versions: branch on `status` and use this for logs.
     * </pre>
     *
     * <code>string pipes_status = 6;</code>
     * @return The pipesStatus.
     */
    public java.lang.String getPipesStatus() {
      java.lang.Object ref = pipesStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pipesStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The raw pipes result `status` was derived from (e.g. "PARSE_SUCCESS", "TIMEOUT";
     * see org.apache.tika.pipes.api.PipesResult.RESULT_STATUS). Its values can change
     * between Tika versions: branch on `status` and use this for logs.
     * </pre>
     *
     * <code>string pipes_status = 6;</code>
     * @return The bytes for pipesStatus.
     */
    public com.google.protobuf.ByteString
        getPipesStatusBytes() {
      java.lang.Object ref = pipesStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pipesStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The raw pipes result `status` was derived from (e.g. "PARSE_SUCCESS", "TIMEOUT";
     * see org.apache.tika.pipes.api.PipesResult.RESULT_STATUS). Its values can change
     * between Tika versions: branch on `status` and use this for logs.
     * </pre>
     *
     * <code>string pipes_status = 6;</code>
     * @param value The pipesStatus to set.
     * @return This builder for chaining.
     */
    public Builder setPipesStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pipesStatus_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The raw pipes result `status` was derived from (e.g. "PARSE_SUCCESS", "TIMEOUT";
     * see org.apache.tika.pipes.api.PipesResult.RESULT_STATUS). Its values can change
     * between Tika versions: branch on `status` and use this for logs.
     * </pre>
     *
     * <code>string pipes_status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPipesStatus() {
      pipesStatus_ = getDefaultInstance().getPipesStatus();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The raw pipes result `status` was derived from (e.g. "PARSE_SUCCESS", "TIMEOUT";
     * see org.apache.tika.pipes.api.PipesResult.RESULT_STATUS). Its values can change
     * between Tika versions: branch on `status` and use this for logs.
     * </pre>
     *
     * <code>string pipes_status = 6;</code>
     * @param value The bytes for pipesStatus to set.
     * @return This builder for chaining.
     */
    public Builder setPipesStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pipesStatus_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.apache.tika.grpc.v2.ParseStatus)
  }

  // @@protoc_insertion_point(class_scope:org.apache.tika.grpc.v2.ParseStatus)
  private static final org.apache.tika.grpc.v2.ParseStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.tika.grpc.v2.ParseStatus();
  }

  public static org.apache.tika.grpc.v2.ParseStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParseStatus>
      PARSER = new com.google.protobuf.AbstractParser<ParseStatus>() {
    @java.lang.Override
    public ParseStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ParseStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParseStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.tika.grpc.v2.ParseStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

