// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/document.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

public interface ParseStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.tika.grpc.v2.ParseStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.apache.tika.grpc.v2.ParseStatus.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.org.apache.tika.grpc.v2.ParseStatus.Status status = 1;</code>
   * @return The status.
   */
  org.apache.tika.grpc.v2.ParseStatus.Status getStatus();

  /**
   * <pre>
   * Milliseconds for the whole fetch and parse, measured by the server. Both happen
   * in the forked pipes worker, so the parse time alone is not available.
   * </pre>
   *
   * <code>int64 fetch_parse_time_ms = 2;</code>
   * @return The fetchParseTimeMs.
   */
  long getFetchParseTimeMs();

  /**
   * <code>repeated string parsers_used = 3;</code>
   * @return A list containing the parsersUsed.
   */
  java.util.List<java.lang.String>
      getParsersUsedList();
  /**
   * <code>repeated string parsers_used = 3;</code>
   * @return The count of parsersUsed.
   */
  int getParsersUsedCount();
  /**
   * <code>repeated string parsers_used = 3;</code>
   * @param index The index of the element to return.
   * @return The parsersUsed at the given index.
   */
  java.lang.String getParsersUsed(int index);
  /**
   * <code>repeated string parsers_used = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the parsersUsed at the given index.
   */
  com.google.protobuf.ByteString
      getParsersUsedBytes(int index);

  /**
   * <code>repeated string errors = 4;</code>
   * @return A list containing the errors.
   */
  java.util.List<java.lang.String>
      getErrorsList();
  /**
   * <code>repeated string errors = 4;</code>
   * @return The count of errors.
   */
  int getErrorsCount();
  /**
   * <code>repeated string errors = 4;</code>
   * @param index The index of the element to return.
   * @return The errors at the given index.
   */
  java.lang.String getErrors(int index);
  /**
   * <code>repeated string errors = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the errors at the given index.
   */
  com.google.protobuf.ByteString
      getErrorsBytes(int index);

  /**
   * <pre>
   * Version string of the Tika that produced this document (e.g. "Apache Tika 4.0.0"),
   * so long-lived stores can tell which producer wrote an entry.
   * </pre>
   *
   * <code>string tika_version = 5;</code>
   * @return The tikaVersion.
   */
  java.lang.String getTikaVersion();
  /**
   * <pre>
   * Version string of the Tika that produced this document (e.g. "Apache Tika 4.0.0"),
   * so long-lived stores can tell which producer wrote an entry.
   * </pre>
   *
   * <code>string tika_version = 5;</code>
   * @return The bytes for tikaVersion.
   */
  com.google.protobuf.ByteString
      getTikaVersionBytes();

  /**
   * <pre>
   * The raw pipes result `status` was derived from (e.g. "PARSE_SUCCESS", "TIMEOUT";
   * see org.apache.tika.pipes.api.PipesResult.RESULT_STATUS). Its values can change
   * between Tika versions: branch on `status` and use this for logs.
   * </pre>
   *
   * <code>string pipes_status = 6;</code>
   * @return The pipesStatus.
   */
  java.lang.String getPipesStatus();
  /**
   * <pre>
   * The raw pipes result `status` was derived from (e.g. "PARSE_SUCCESS", "TIMEOUT";
   * see org.apache.tika.pipes.api.PipesResult.RESULT_STATUS). Its values can change
   * between Tika versions: branch on `status` and use this for logs.
   * </pre>
   *
   * <code>string pipes_status = 6;</code>
   * @return The bytes for pipesStatus.
   */
  com.google.protobuf.ByteString
      getPipesStatusBytes();
}
