// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/tika_v2.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

/**
 * Protobuf type {@code org.apache.tika.grpc.v2.ParseBytesRequest}
 */
public final class ParseBytesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.apache.tika.grpc.v2.ParseBytesRequest)
    ParseBytesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ParseBytesRequest.newBuilder() to construct.
  private ParseBytesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ParseBytesRequest() {
    correlationId_ = "";
    content_ = com.google.protobuf.ByteString.EMPTY;
    resourceName_ = "";
    sourceUri_ = "";
    effectiveUri_ = "";
    baseUri_ = "";
    parseContextJson_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ParseBytesRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_ParseBytesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_ParseBytesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.tika.grpc.v2.ParseBytesRequest.class, org.apache.tika.grpc.v2.ParseBytesRequest.Builder.class);
  }

  public static final int CORRELATION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object correlationId_ = "";
  /**
   * <pre>
   * The caller's id for this request, returned unchanged as Document.id and
   * ParseBytesReply.correlation_id.
   * </pre>
   *
   * <code>string correlation_id = 1;</code>
   * @return The correlationId.
   */
  @java.lang.Override
  public java.lang.String getCorrelationId() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      correlationId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The caller's id for this request, returned unchanged as Document.id and
   * ParseBytesReply.correlation_id.
   * </pre>
   *
   * <code>string correlation_id = 1;</code>
   * @return The bytes for correlationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCorrelationIdBytes() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      correlationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Bytes to parse. Required, at most the server's parseBytesMaxContentBytes. The
   * whole request must also fit the server's gRPC inbound limit: 4 MiB unless
   * maxInboundMessageBytes sets another value.
   * </pre>
   *
   * <code>bytes content = 2;</code>
   * @return The content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getContent() {
    return content_;
  }

  public static final int RESOURCE_NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resourceName_ = "";
  /**
   * <pre>
   * Optional file name, such as "page.html". Tika uses it to detect the content type
   * and returns it as Document.origin.filename.
   * </pre>
   *
   * <code>string resource_name = 3;</code>
   * @return The resourceName.
   */
  @java.lang.Override
  public java.lang.String getResourceName() {
    java.lang.Object ref = resourceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional file name, such as "page.html". Tika uses it to detect the content type
   * and returns it as Document.origin.filename.
   * </pre>
   *
   * <code>string resource_name = 3;</code>
   * @return The bytes for resourceName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceNameBytes() {
    java.lang.Object ref = resourceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_URI_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceUri_ = "";
  /**
   * <pre>
   * Optional URIs the caller records for the bytes, such as the requested URL, the
   * URL after redirects and the base URL for relative links. Tika returns them in
   * Document.origin and does not use them.
   * </pre>
   *
   * <code>string source_uri = 4;</code>
   * @return The sourceUri.
   */
  @java.lang.Override
  public java.lang.String getSourceUri() {
    java.lang.Object ref = sourceUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceUri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional URIs the caller records for the bytes, such as the requested URL, the
   * URL after redirects and the base URL for relative links. Tika returns them in
   * Document.origin and does not use them.
   * </pre>
   *
   * <code>string source_uri = 4;</code>
   * @return The bytes for sourceUri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceUriBytes() {
    java.lang.Object ref = sourceUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EFFECTIVE_URI_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object effectiveUri_ = "";
  /**
   * <code>string effective_uri = 5;</code>
   * @return The effectiveUri.
   */
  @java.lang.Override
  public java.lang.String getEffectiveUri() {
    java.lang.Object ref = effectiveUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      effectiveUri_ = s;
      return s;
    }
  }
  /**
   * <code>string effective_uri = 5;</code>
   * @return The bytes for effectiveUri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEffectiveUriBytes() {
    java.lang.Object ref = effectiveUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      effectiveUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BASE_URI_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object baseUri_ = "";
  /**
   * <code>string base_uri = 6;</code>
   * @return The baseUri.
   */
  @java.lang.Override
  public java.lang.String getBaseUri() {
    java.lang.Object ref = baseUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      baseUri_ = s;
      return s;
    }
  }
  /**
   * <code>string base_uri = 6;</code>
   * @return The bytes for baseUri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBaseUriBytes() {
    java.lang.Object ref = baseUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      baseUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRUNCATED_FIELD_NUMBER = 7;
  private boolean truncated_ = false;
  /**
   * <pre>
   * Set when the caller cut the bytes short, for example at a crawler's size limit.
   * Returned as Document.origin.truncated.
   * </pre>
   *
   * <code>bool truncated = 7;</code>
   * @return The truncated.
   */
  @java.lang.Override
  public boolean getTruncated() {
    return truncated_;
  }

  public static final int PARSE_CONTEXT_JSON_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parseContextJson_ = "";
  /**
   * <pre>
   * Optional JSON object to configure the ParseContext for this request.
   * </pre>
   *
   * <code>string parse_context_json = 8;</code>
   * @return The parseContextJson.
   */
  @java.lang.Override
  public java.lang.String getParseContextJson() {
    java.lang.Object ref = parseContextJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parseContextJson_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional JSON object to configure the ParseContext for this request.
   * </pre>
   *
   * <code>string parse_context_json = 8;</code>
   * @return The bytes for parseContextJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParseContextJsonBytes() {
    java.lang.Object ref = parseContextJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parseContextJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(correlationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, correlationId_);
    }
    if (!content_.isEmpty()) {
      output.writeBytes(2, content_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resourceName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resourceName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceUri_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sourceUri_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(effectiveUri_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, effectiveUri_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseUri_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, baseUri_);
    }
    if (truncated_ != false) {
      output.writeBool(7, truncated_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parseContextJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, parseContextJson_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(correlationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, correlationId_);
    }
    if (!content_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, content_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resourceName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, resourceName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceUri_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sourceUri_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(effectiveUri_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, effectiveUri_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseUri_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, baseUri_);
    }
    if (truncated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, truncated_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parseContextJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, parseContextJson_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.tika.grpc.v2.ParseBytesRequest)) {
      return super.equals(obj);
    }
    org.apache.tika.grpc.v2.ParseBytesRequest other = (org.apache.tika.grpc.v2.ParseBytesRequest) obj;

    if (!getCorrelationId()
        .equals(other.getCorrelationId())) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getResourceName()
        .equals(other.getResourceName())) return false;
    if (!getSourceUri()
        .equals(other.getSourceUri())) return false;
    if (!getEffectiveUri()
        .equals(other.getEffectiveUri())) return false;
    if (!getBaseUri()
        .equals(other.getBaseUri())) return false;
    if (getTruncated()
        != other.getTruncated()) return false;
    if (!getParseContextJson()
        .equals(other.getParseContextJson())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CORRELATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCorrelationId().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + RESOURCE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getResourceName().hashCode();
    hash = (37 * hash) + SOURCE_URI_FIELD_NUMBER;
    hash = (53 * hash) + getSourceUri().hashCode();
    hash = (37 * hash) + EFFECTIVE_URI_FIELD_NUMBER;
    hash = (53 * hash) + getEffectiveUri().hashCode();
    hash = (37 * hash) + BASE_URI_FIELD_NUMBER;
    hash = (53 * hash) + getBaseUri().hashCode();
    hash = (37 * hash) + TRUNCATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTruncated());
    hash = (37 * hash) + PARSE_CONTEXT_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getParseContextJson().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.tika.grpc.v2.ParseBytesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.ParseBytesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.ParseBytesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.ParseBytesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.ParseBytesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.ParseBytesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.ParseBytesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.ParseBytesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.apache.tika.grpc.v2.ParseBytesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.apache.tika.grpc.v2.ParseBytesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.ParseBytesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.ParseBytesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.tika.grpc.v2.ParseBytesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.apache.tika.grpc.v2.ParseBytesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.apache.tika.grpc.v2.ParseBytesRequest)
      org.apache.tika.grpc.v2.ParseBytesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_ParseBytesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_ParseBytesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.tika.grpc.v2.ParseBytesRequest.class, org.apache.tika.grpc.v2.ParseBytesRequest.Builder.class);
    }

    // Construct using org.apache.tika.grpc.v2.ParseBytesRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      correlationId_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
      resourceName_ = "";
      sourceUri_ = "";
      effectiveUri_ = "";
      baseUri_ = "";
      truncated_ = false;
      parseContextJson_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_ParseBytesRequest_descriptor;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.ParseBytesRequest getDefaultInstanceForType() {
      return org.apache.tika.grpc.v2.ParseBytesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.ParseBytesRequest build() {
      org.apache.tika.grpc.v2.ParseBytesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.ParseBytesRequest buildPartial() {
      org.apache.tika.grpc.v2.ParseBytesRequest result = new org.apache.tika.grpc.v2.ParseBytesRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.tika.grpc.v2.ParseBytesRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.correlationId_ = correlationId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.content_ = content_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.resourceName_ = resourceName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sourceUri_ = sourceUri_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.effectiveUri_ = effectiveUri_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.baseUri_ = baseUri_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.truncated_ = truncated_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.parseContextJson_ = parseContextJson_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.tika.grpc.v2.ParseBytesRequest) {
        return mergeFrom((org.apache.tika.grpc.v2.ParseBytesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.tika.grpc.v2.ParseBytesRequest other) {
      if (other == org.apache.tika.grpc.v2.ParseBytesRequest.getDefaultInstance()) return this;
      if (!other.getCorrelationId().isEmpty()) {
        correlationId_ = other.correlationId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
        setContent(other.getContent());
      }
      if (!other.getResourceName().isEmpty()) {
        resourceName_ = other.resourceName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSourceUri().isEmpty()) {
        sourceUri_ = other.sourceUri_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getEffectiveUri().isEmpty()) {
        effectiveUri_ = other.effectiveUri_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getBaseUri().isEmpty()) {
        baseUri_ = other.baseUri_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getTruncated() != false) {
        setTruncated(other.getTruncated());
      }
      if (!other.getParseContextJson().isEmpty()) {
        parseContextJson_ = other.parseContextJson_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              correlationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              content_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              resourceName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              sourceUri_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              effectiveUri_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              baseUri_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              truncated_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              parseContextJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object correlationId_ = "";
    /**
     * <pre>
     * The caller's id for this request, returned unchanged as Document.id and
     * ParseBytesReply.correlation_id.
     * </pre>
     *
     * <code>string correlation_id = 1;</code>
     * @return The correlationId.
     */
    public java.lang.String getCorrelationId() {
      java.lang.Object ref = correlationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correlationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The caller's id for this request, returned unchanged as Document.id and
     * ParseBytesReply.correlation_id.
     * </pre>
     *
     * <code>string correlation_id = 1;</code>
     * @return The bytes for correlationId.
     */
    public com.google.protobuf.ByteString
        getCorrelationIdBytes() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The caller's id for this request, returned unchanged as Document.id and
     * ParseBytesReply.correlation_id.
     * </pre>
     *
     * <code>string correlation_id = 1;</code>
     * @param value The correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      correlationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The caller's id for this request, returned unchanged as Document.id and
     * ParseBytesReply.correlation_id.
     * </pre>
     *
     * <code>string correlation_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorrelationId() {
      correlationId_ = getDefaultInstance().getCorrelationId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The caller's id for this request, returned unchanged as Document.id and
     * ParseBytesReply.correlation_id.
     * </pre>
     *
     * <code>string correlation_id = 1;</code>
     * @param value The bytes for correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      correlationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Bytes to parse. Required, at most the server's parseBytesMaxContentBytes. The
     * whole request must also fit the server's gRPC inbound limit: 4 MiB unless
     * maxInboundMessageBytes sets another value.
     * </pre>
     *
     * <code>bytes content = 2;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    /**
     * <pre>
     * Bytes to parse. Required, at most the server's parseBytesMaxContentBytes. The
     * whole request must also fit the server's gRPC inbound limit: 4 MiB unless
     * maxInboundMessageBytes sets another value.
     * </pre>
     *
     * <code>bytes content = 2;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      content_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Bytes to parse. Required, at most the server's parseBytesMaxContentBytes. The
     * whole request must also fit the server's gRPC inbound limit: 4 MiB unless
     * maxInboundMessageBytes sets another value.
     * </pre>
     *
     * <code>bytes content = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      bitField0_ = (bitField0_ & ~0x00000002);
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }

    private java.lang.Object resourceName_ = "";
    /**
     * <pre>
     * Optional file name, such as "page.html". Tika uses it to detect the content type
     * and returns it as Document.origin.filename.
     * </pre>
     *
     * <code>string resource_name = 3;</code>
     * @return The resourceName.
     */
    public java.lang.String getResourceName() {
      java.lang.Object ref = resourceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional file name, such as "page.html". Tika uses it to detect the content type
     * and returns it as Document.origin.filename.
     * </pre>
     *
     * <code>string resource_name = 3;</code>
     * @return The bytes for resourceName.
     */
    public com.google.protobuf.ByteString
        getResourceNameBytes() {
      java.lang.Object ref = resourceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional file name, such as "page.html". Tika uses it to detect the content type
     * and returns it as Document.origin.filename.
     * </pre>
     *
     * <code>string resource_name = 3;</code>
     * @param value The resourceName to set.
     * @return This builder for chaining.
     */
    public Builder setResourceName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resourceName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional file name, such as "page.html". Tika uses it to detect the content type
     * and returns it as Document.origin.filename.
     * </pre>
     *
     * <code>string resource_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearResourceName() {
      resourceName_ = getDefaultInstance().getResourceName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional file name, such as "page.html". Tika uses it to detect the content type
     * and returns it as Document.origin.filename.
     * </pre>
     *
     * <code>string resource_name = 3;</code>
     * @param value The bytes for resourceName to set.
     * @return This builder for chaining.
     */
    public Builder setResourceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resourceName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object sourceUri_ = "";
    /**
     * <pre>
     * Optional URIs the caller records for the bytes, such as the requested URL, the
     * URL after redirects and the base URL for relative links. Tika returns them in
     * Document.origin and does not use them.
     * </pre>
     *
     * <code>string source_uri = 4;</code>
     * @return The sourceUri.
     */
    public java.lang.String getSourceUri() {
      java.lang.Object ref = sourceUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional URIs the caller records for the bytes, such as the requested URL, the
     * URL after redirects and the base URL for relative links. Tika returns them in
     * Document.origin and does not use them.
     * </pre>
     *
     * <code>string source_uri = 4;</code>
     * @return The bytes for sourceUri.
     */
    public com.google.protobuf.ByteString
        getSourceUriBytes() {
      java.lang.Object ref = sourceUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional URIs the caller records for the bytes, such as the requested URL, the
     * URL after redirects and the base URL for relative links. Tika returns them in
     * Document.origin and does not use them.
     * </pre>
     *
     * <code>string source_uri = 4;</code>
     * @param value The sourceUri to set.
     * @return This builder for chaining.
     */
    public Builder setSourceUri(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceUri_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional URIs the caller records for the bytes, such as the requested URL, the
     * URL after redirects and the base URL for relative links. Tika returns them in
     * Document.origin and does not use them.
     * </pre>
     *
     * <code>string source_uri = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceUri() {
      sourceUri_ = getDefaultInstance().getSourceUri();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional URIs the caller records for the bytes, such as the requested URL, the
     * URL after redirects and the base URL for relative links. Tika returns them in
     * Document.origin and does not use them.
     * </pre>
     *
     * <code>string source_uri = 4;</code>
     * @param value The bytes for sourceUri to set.
     * @return This builder for chaining.
     */
    public Builder setSourceUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceUri_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object effectiveUri_ = "";
    /**
     * <code>string effective_uri = 5;</code>
     * @return The effectiveUri.
     */
    public java.lang.String getEffectiveUri() {
      java.lang.Object ref = effectiveUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        effectiveUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string effective_uri = 5;</code>
     * @return The bytes for effectiveUri.
     */
    public com.google.protobuf.ByteString
        getEffectiveUriBytes() {
      java.lang.Object ref = effectiveUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        effectiveUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string effective_uri = 5;</code>
     * @param value The effectiveUri to set.
     * @return This builder for chaining.
     */
    public Builder setEffectiveUri(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      effectiveUri_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string effective_uri = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEffectiveUri() {
      effectiveUri_ = getDefaultInstance().getEffectiveUri();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string effective_uri = 5;</code>
     * @param value The bytes for effectiveUri to set.
     * @return This builder for chaining.
     */
    public Builder setEffectiveUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      effectiveUri_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object baseUri_ = "";
    /**
     * <code>string base_uri = 6;</code>
     * @return The baseUri.
     */
    public java.lang.String getBaseUri() {
      java.lang.Object ref = baseUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string base_uri = 6;</code>
     * @return The bytes for baseUri.
     */
    public com.google.protobuf.ByteString
        getBaseUriBytes() {
      java.lang.Object ref = baseUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string base_uri = 6;</code>
     * @param value The baseUri to set.
     * @return This builder for chaining.
     */
    public Builder setBaseUri(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      baseUri_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string base_uri = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBaseUri() {
      baseUri_ = getDefaultInstance().getBaseUri();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string base_uri = 6;</code>
     * @param value The bytes for baseUri to set.
     * @return This builder for chaining.
     */
    public Builder setBaseUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      baseUri_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private boolean truncated_ ;
    /**
     * <pre>
     * Set when the caller cut the bytes short, for example at a crawler's size limit.
     * Returned as Document.origin.truncated.
     * </pre>
     *
     * <code>bool truncated = 7;</code>
     * @return The truncated.
     */
    @java.lang.Override
    public boolean getTruncated() {
      return truncated_;
    }
    /**
     * <pre>
     * Set when the caller cut the bytes short, for example at a crawler's size limit.
     * Returned as Document.origin.truncated.
     * </pre>
     *
     * <code>bool truncated = 7;</code>
     * @param value The truncated to set.
     * @return This builder for chaining.
     */
    public Builder setTruncated(boolean value) {

      truncated_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Set when the caller cut the bytes short, for example at a crawler's size limit.
     * Returned as Document.origin.truncated.
     * </pre>
     *
     * <code>bool truncated = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTruncated() {
      bitField0_ = (bitField0_ & ~0x00000040);
      truncated_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object parseContextJson_ = "";
    /**
     * <pre>
     * Optional JSON object to configure the ParseContext for this request.
     * </pre>
     *
     * <code>string parse_context_json = 8;</code>
     * @return The parseContextJson.
     */
    public java.lang.String getParseContextJson() {
      java.lang.Object ref = parseContextJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parseContextJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional JSON object to configure the ParseContext for this request.
     * </pre>
     *
     * <code>string parse_context_json = 8;</code>
     * @return The bytes for parseContextJson.
     */
    public com.google.protobuf.ByteString
        getParseContextJsonBytes() {
      java.lang.Object ref = parseContextJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parseContextJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional JSON object to configure the ParseContext for this request.
     * </pre>
     *
     * <code>string parse_context_json = 8;</code>
     * @param value The parseContextJson to set.
     * @return This builder for chaining.
     */
    public Builder setParseContextJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parseContextJson_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional JSON object to configure the ParseContext for this request.
     * </pre>
     *
     * <code>string parse_context_json = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearParseContextJson() {
      parseContextJson_ = getDefaultInstance().getParseContextJson();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional JSON object to configure the ParseContext for this request.
     * </pre>
     *
     * <code>string parse_context_json = 8;</code>
     * @param value The bytes for parseContextJson to set.
     * @return This builder for chaining.
     */
    public Builder setParseContextJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parseContextJson_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.apache.tika.grpc.v2.ParseBytesRequest)
  }

  // @@protoc_insertion_point(class_scope:org.apache.tika.grpc.v2.ParseBytesRequest)
  private static final org.apache.tika.grpc.v2.ParseBytesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.tika.grpc.v2.ParseBytesRequest();
  }

  public static org.apache.tika.grpc.v2.ParseBytesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParseBytesRequest>
      PARSER = new com.google.protobuf.AbstractParser<ParseBytesRequest>() {
    @java.lang.Override
    public ParseBytesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ParseBytesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParseBytesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.tika.grpc.v2.ParseBytesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

