// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/document.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

/**
 * Protobuf type {@code org.apache.tika.grpc.v2.SourceOrigin}
 */
public final class SourceOrigin extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.apache.tika.grpc.v2.SourceOrigin)
    SourceOriginOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SourceOrigin.newBuilder() to construct.
  private SourceOrigin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SourceOrigin() {
    filename_ = "";
    parser_ = "";
    sha256_ = "";
    sourceUri_ = "";
    effectiveUri_ = "";
    baseUri_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SourceOrigin();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_SourceOrigin_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_SourceOrigin_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.tika.grpc.v2.SourceOrigin.class, org.apache.tika.grpc.v2.SourceOrigin.Builder.class);
  }

  public static final int FILENAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object filename_ = "";
  /**
   * <code>string filename = 1;</code>
   * @return The filename.
   */
  @java.lang.Override
  public java.lang.String getFilename() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filename_ = s;
      return s;
    }
  }
  /**
   * <code>string filename = 1;</code>
   * @return The bytes for filename.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilenameBytes() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BYTE_SIZE_FIELD_NUMBER = 2;
  private long byteSize_ = 0L;
  /**
   * <code>int64 byte_size = 2;</code>
   * @return The byteSize.
   */
  @java.lang.Override
  public long getByteSize() {
    return byteSize_;
  }

  public static final int PARSER_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parser_ = "";
  /**
   * <code>string parser = 3;</code>
   * @return The parser.
   */
  @java.lang.Override
  public java.lang.String getParser() {
    java.lang.Object ref = parser_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parser_ = s;
      return s;
    }
  }
  /**
   * <code>string parser = 3;</code>
   * @return The bytes for parser.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParserBytes() {
    java.lang.Object ref = parser_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parser_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHA256_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sha256_ = "";
  /**
   * <pre>
   * Hex-encoded SHA-256 of the source bytes, taken from the digest the parse pipeline
   * recorded (the tk:digest:SHA-256 metadata value). Empty when the pipeline has no
   * digester configured. Downstream consumers use it to tie derived artifacts
   * (annotations, index entries) back to the exact bytes that were parsed.
   * </pre>
   *
   * <code>string sha256 = 4;</code>
   * @return The sha256.
   */
  @java.lang.Override
  public java.lang.String getSha256() {
    java.lang.Object ref = sha256_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sha256_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Hex-encoded SHA-256 of the source bytes, taken from the digest the parse pipeline
   * recorded (the tk:digest:SHA-256 metadata value). Empty when the pipeline has no
   * digester configured. Downstream consumers use it to tie derived artifacts
   * (annotations, index entries) back to the exact bytes that were parsed.
   * </pre>
   *
   * <code>string sha256 = 4;</code>
   * @return The bytes for sha256.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSha256Bytes() {
    java.lang.Object ref = sha256_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sha256_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_URI_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceUri_ = "";
  /**
   * <pre>
   * Set only by ParseBytes, from the request; empty for FetchAndParse. The URIs the
   * caller recorded for the bytes, which Tika does not use, and whether the caller
   * cut the bytes short.
   * </pre>
   *
   * <code>string source_uri = 5;</code>
   * @return The sourceUri.
   */
  @java.lang.Override
  public java.lang.String getSourceUri() {
    java.lang.Object ref = sourceUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceUri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Set only by ParseBytes, from the request; empty for FetchAndParse. The URIs the
   * caller recorded for the bytes, which Tika does not use, and whether the caller
   * cut the bytes short.
   * </pre>
   *
   * <code>string source_uri = 5;</code>
   * @return The bytes for sourceUri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceUriBytes() {
    java.lang.Object ref = sourceUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EFFECTIVE_URI_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object effectiveUri_ = "";
  /**
   * <code>string effective_uri = 6;</code>
   * @return The effectiveUri.
   */
  @java.lang.Override
  public java.lang.String getEffectiveUri() {
    java.lang.Object ref = effectiveUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      effectiveUri_ = s;
      return s;
    }
  }
  /**
   * <code>string effective_uri = 6;</code>
   * @return The bytes for effectiveUri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEffectiveUriBytes() {
    java.lang.Object ref = effectiveUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      effectiveUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BASE_URI_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object baseUri_ = "";
  /**
   * <code>string base_uri = 7;</code>
   * @return The baseUri.
   */
  @java.lang.Override
  public java.lang.String getBaseUri() {
    java.lang.Object ref = baseUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      baseUri_ = s;
      return s;
    }
  }
  /**
   * <code>string base_uri = 7;</code>
   * @return The bytes for baseUri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBaseUriBytes() {
    java.lang.Object ref = baseUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      baseUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRUNCATED_FIELD_NUMBER = 8;
  private boolean truncated_ = false;
  /**
   * <code>bool truncated = 8;</code>
   * @return The truncated.
   */
  @java.lang.Override
  public boolean getTruncated() {
    return truncated_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filename_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filename_);
    }
    if (byteSize_ != 0L) {
      output.writeInt64(2, byteSize_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parser_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, parser_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sha256_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sha256_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceUri_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sourceUri_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(effectiveUri_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, effectiveUri_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseUri_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, baseUri_);
    }
    if (truncated_ != false) {
      output.writeBool(8, truncated_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filename_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filename_);
    }
    if (byteSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, byteSize_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parser_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, parser_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sha256_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sha256_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceUri_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sourceUri_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(effectiveUri_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, effectiveUri_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseUri_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, baseUri_);
    }
    if (truncated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, truncated_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.tika.grpc.v2.SourceOrigin)) {
      return super.equals(obj);
    }
    org.apache.tika.grpc.v2.SourceOrigin other = (org.apache.tika.grpc.v2.SourceOrigin) obj;

    if (!getFilename()
        .equals(other.getFilename())) return false;
    if (getByteSize()
        != other.getByteSize()) return false;
    if (!getParser()
        .equals(other.getParser())) return false;
    if (!getSha256()
        .equals(other.getSha256())) return false;
    if (!getSourceUri()
        .equals(other.getSourceUri())) return false;
    if (!getEffectiveUri()
        .equals(other.getEffectiveUri())) return false;
    if (!getBaseUri()
        .equals(other.getBaseUri())) return false;
    if (getTruncated()
        != other.getTruncated()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFilename().hashCode();
    hash = (37 * hash) + BYTE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getByteSize());
    hash = (37 * hash) + PARSER_FIELD_NUMBER;
    hash = (53 * hash) + getParser().hashCode();
    hash = (37 * hash) + SHA256_FIELD_NUMBER;
    hash = (53 * hash) + getSha256().hashCode();
    hash = (37 * hash) + SOURCE_URI_FIELD_NUMBER;
    hash = (53 * hash) + getSourceUri().hashCode();
    hash = (37 * hash) + EFFECTIVE_URI_FIELD_NUMBER;
    hash = (53 * hash) + getEffectiveUri().hashCode();
    hash = (37 * hash) + BASE_URI_FIELD_NUMBER;
    hash = (53 * hash) + getBaseUri().hashCode();
    hash = (37 * hash) + TRUNCATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTruncated());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.tika.grpc.v2.SourceOrigin parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.SourceOrigin parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.SourceOrigin parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.SourceOrigin parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.SourceOrigin parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.SourceOrigin parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.SourceOrigin parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.SourceOrigin parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.apache.tika.grpc.v2.SourceOrigin parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.apache.tika.grpc.v2.SourceOrigin parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.SourceOrigin parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.SourceOrigin parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.tika.grpc.v2.SourceOrigin prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.apache.tika.grpc.v2.SourceOrigin}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.apache.tika.grpc.v2.SourceOrigin)
      org.apache.tika.grpc.v2.SourceOriginOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_SourceOrigin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_SourceOrigin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.tika.grpc.v2.SourceOrigin.class, org.apache.tika.grpc.v2.SourceOrigin.Builder.class);
    }

    // Construct using org.apache.tika.grpc.v2.SourceOrigin.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      filename_ = "";
      byteSize_ = 0L;
      parser_ = "";
      sha256_ = "";
      sourceUri_ = "";
      effectiveUri_ = "";
      baseUri_ = "";
      truncated_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.tika.grpc.v2.DocumentOuterClass.internal_static_org_apache_tika_grpc_v2_SourceOrigin_descriptor;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.SourceOrigin getDefaultInstanceForType() {
      return org.apache.tika.grpc.v2.SourceOrigin.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.SourceOrigin build() {
      org.apache.tika.grpc.v2.SourceOrigin result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.SourceOrigin buildPartial() {
      org.apache.tika.grpc.v2.SourceOrigin result = new org.apache.tika.grpc.v2.SourceOrigin(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.tika.grpc.v2.SourceOrigin result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.filename_ = filename_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.byteSize_ = byteSize_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.parser_ = parser_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sha256_ = sha256_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sourceUri_ = sourceUri_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.effectiveUri_ = effectiveUri_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.baseUri_ = baseUri_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.truncated_ = truncated_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.tika.grpc.v2.SourceOrigin) {
        return mergeFrom((org.apache.tika.grpc.v2.SourceOrigin)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.tika.grpc.v2.SourceOrigin other) {
      if (other == org.apache.tika.grpc.v2.SourceOrigin.getDefaultInstance()) return this;
      if (!other.getFilename().isEmpty()) {
        filename_ = other.filename_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getByteSize() != 0L) {
        setByteSize(other.getByteSize());
      }
      if (!other.getParser().isEmpty()) {
        parser_ = other.parser_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSha256().isEmpty()) {
        sha256_ = other.sha256_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getSourceUri().isEmpty()) {
        sourceUri_ = other.sourceUri_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getEffectiveUri().isEmpty()) {
        effectiveUri_ = other.effectiveUri_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getBaseUri().isEmpty()) {
        baseUri_ = other.baseUri_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getTruncated() != false) {
        setTruncated(other.getTruncated());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              filename_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              byteSize_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              parser_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              sha256_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              sourceUri_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              effectiveUri_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              baseUri_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              truncated_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object filename_ = "";
    /**
     * <code>string filename = 1;</code>
     * @return The filename.
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string filename = 1;</code>
     * @return The bytes for filename.
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string filename = 1;</code>
     * @param value The filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilename(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      filename_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string filename = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilename() {
      filename_ = getDefaultInstance().getFilename();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string filename = 1;</code>
     * @param value The bytes for filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      filename_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long byteSize_ ;
    /**
     * <code>int64 byte_size = 2;</code>
     * @return The byteSize.
     */
    @java.lang.Override
    public long getByteSize() {
      return byteSize_;
    }
    /**
     * <code>int64 byte_size = 2;</code>
     * @param value The byteSize to set.
     * @return This builder for chaining.
     */
    public Builder setByteSize(long value) {

      byteSize_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 byte_size = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearByteSize() {
      bitField0_ = (bitField0_ & ~0x00000002);
      byteSize_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object parser_ = "";
    /**
     * <code>string parser = 3;</code>
     * @return The parser.
     */
    public java.lang.String getParser() {
      java.lang.Object ref = parser_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parser_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string parser = 3;</code>
     * @return The bytes for parser.
     */
    public com.google.protobuf.ByteString
        getParserBytes() {
      java.lang.Object ref = parser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string parser = 3;</code>
     * @param value The parser to set.
     * @return This builder for chaining.
     */
    public Builder setParser(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parser_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string parser = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearParser() {
      parser_ = getDefaultInstance().getParser();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string parser = 3;</code>
     * @param value The bytes for parser to set.
     * @return This builder for chaining.
     */
    public Builder setParserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parser_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object sha256_ = "";
    /**
     * <pre>
     * Hex-encoded SHA-256 of the source bytes, taken from the digest the parse pipeline
     * recorded (the tk:digest:SHA-256 metadata value). Empty when the pipeline has no
     * digester configured. Downstream consumers use it to tie derived artifacts
     * (annotations, index entries) back to the exact bytes that were parsed.
     * </pre>
     *
     * <code>string sha256 = 4;</code>
     * @return The sha256.
     */
    public java.lang.String getSha256() {
      java.lang.Object ref = sha256_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sha256_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Hex-encoded SHA-256 of the source bytes, taken from the digest the parse pipeline
     * recorded (the tk:digest:SHA-256 metadata value). Empty when the pipeline has no
     * digester configured. Downstream consumers use it to tie derived artifacts
     * (annotations, index entries) back to the exact bytes that were parsed.
     * </pre>
     *
     * <code>string sha256 = 4;</code>
     * @return The bytes for sha256.
     */
    public com.google.protobuf.ByteString
        getSha256Bytes() {
      java.lang.Object ref = sha256_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sha256_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Hex-encoded SHA-256 of the source bytes, taken from the digest the parse pipeline
     * recorded (the tk:digest:SHA-256 metadata value). Empty when the pipeline has no
     * digester configured. Downstream consumers use it to tie derived artifacts
     * (annotations, index entries) back to the exact bytes that were parsed.
     * </pre>
     *
     * <code>string sha256 = 4;</code>
     * @param value The sha256 to set.
     * @return This builder for chaining.
     */
    public Builder setSha256(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sha256_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Hex-encoded SHA-256 of the source bytes, taken from the digest the parse pipeline
     * recorded (the tk:digest:SHA-256 metadata value). Empty when the pipeline has no
     * digester configured. Downstream consumers use it to tie derived artifacts
     * (annotations, index entries) back to the exact bytes that were parsed.
     * </pre>
     *
     * <code>string sha256 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSha256() {
      sha256_ = getDefaultInstance().getSha256();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Hex-encoded SHA-256 of the source bytes, taken from the digest the parse pipeline
     * recorded (the tk:digest:SHA-256 metadata value). Empty when the pipeline has no
     * digester configured. Downstream consumers use it to tie derived artifacts
     * (annotations, index entries) back to the exact bytes that were parsed.
     * </pre>
     *
     * <code>string sha256 = 4;</code>
     * @param value The bytes for sha256 to set.
     * @return This builder for chaining.
     */
    public Builder setSha256Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sha256_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object sourceUri_ = "";
    /**
     * <pre>
     * Set only by ParseBytes, from the request; empty for FetchAndParse. The URIs the
     * caller recorded for the bytes, which Tika does not use, and whether the caller
     * cut the bytes short.
     * </pre>
     *
     * <code>string source_uri = 5;</code>
     * @return The sourceUri.
     */
    public java.lang.String getSourceUri() {
      java.lang.Object ref = sourceUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Set only by ParseBytes, from the request; empty for FetchAndParse. The URIs the
     * caller recorded for the bytes, which Tika does not use, and whether the caller
     * cut the bytes short.
     * </pre>
     *
     * <code>string source_uri = 5;</code>
     * @return The bytes for sourceUri.
     */
    public com.google.protobuf.ByteString
        getSourceUriBytes() {
      java.lang.Object ref = sourceUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Set only by ParseBytes, from the request; empty for FetchAndParse. The URIs the
     * caller recorded for the bytes, which Tika does not use, and whether the caller
     * cut the bytes short.
     * </pre>
     *
     * <code>string source_uri = 5;</code>
     * @param value The sourceUri to set.
     * @return This builder for chaining.
     */
    public Builder setSourceUri(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceUri_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Set only by ParseBytes, from the request; empty for FetchAndParse. The URIs the
     * caller recorded for the bytes, which Tika does not use, and whether the caller
     * cut the bytes short.
     * </pre>
     *
     * <code>string source_uri = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceUri() {
      sourceUri_ = getDefaultInstance().getSourceUri();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Set only by ParseBytes, from the request; empty for FetchAndParse. The URIs the
     * caller recorded for the bytes, which Tika does not use, and whether the caller
     * cut the bytes short.
     * </pre>
     *
     * <code>string source_uri = 5;</code>
     * @param value The bytes for sourceUri to set.
     * @return This builder for chaining.
     */
    public Builder setSourceUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceUri_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object effectiveUri_ = "";
    /**
     * <code>string effective_uri = 6;</code>
     * @return The effectiveUri.
     */
    public java.lang.String getEffectiveUri() {
      java.lang.Object ref = effectiveUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        effectiveUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string effective_uri = 6;</code>
     * @return The bytes for effectiveUri.
     */
    public com.google.protobuf.ByteString
        getEffectiveUriBytes() {
      java.lang.Object ref = effectiveUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        effectiveUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string effective_uri = 6;</code>
     * @param value The effectiveUri to set.
     * @return This builder for chaining.
     */
    public Builder setEffectiveUri(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      effectiveUri_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string effective_uri = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEffectiveUri() {
      effectiveUri_ = getDefaultInstance().getEffectiveUri();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string effective_uri = 6;</code>
     * @param value The bytes for effectiveUri to set.
     * @return This builder for chaining.
     */
    public Builder setEffectiveUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      effectiveUri_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object baseUri_ = "";
    /**
     * <code>string base_uri = 7;</code>
     * @return The baseUri.
     */
    public java.lang.String getBaseUri() {
      java.lang.Object ref = baseUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string base_uri = 7;</code>
     * @return The bytes for baseUri.
     */
    public com.google.protobuf.ByteString
        getBaseUriBytes() {
      java.lang.Object ref = baseUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string base_uri = 7;</code>
     * @param value The baseUri to set.
     * @return This builder for chaining.
     */
    public Builder setBaseUri(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      baseUri_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string base_uri = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearBaseUri() {
      baseUri_ = getDefaultInstance().getBaseUri();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string base_uri = 7;</code>
     * @param value The bytes for baseUri to set.
     * @return This builder for chaining.
     */
    public Builder setBaseUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      baseUri_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private boolean truncated_ ;
    /**
     * <code>bool truncated = 8;</code>
     * @return The truncated.
     */
    @java.lang.Override
    public boolean getTruncated() {
      return truncated_;
    }
    /**
     * <code>bool truncated = 8;</code>
     * @param value The truncated to set.
     * @return This builder for chaining.
     */
    public Builder setTruncated(boolean value) {

      truncated_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool truncated = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTruncated() {
      bitField0_ = (bitField0_ & ~0x00000080);
      truncated_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.apache.tika.grpc.v2.SourceOrigin)
  }

  // @@protoc_insertion_point(class_scope:org.apache.tika.grpc.v2.SourceOrigin)
  private static final org.apache.tika.grpc.v2.SourceOrigin DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.tika.grpc.v2.SourceOrigin();
  }

  public static org.apache.tika.grpc.v2.SourceOrigin getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SourceOrigin>
      PARSER = new com.google.protobuf.AbstractParser<SourceOrigin>() {
    @java.lang.Override
    public SourceOrigin parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SourceOrigin> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SourceOrigin> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.tika.grpc.v2.SourceOrigin getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

