// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/tika_v2.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

public final class TikaV2Proto {
  private TikaV2Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_tika_grpc_v2_FetchAndParseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_tika_grpc_v2_FetchAndParseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_tika_grpc_v2_FetchAndParseReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_tika_grpc_v2_FetchAndParseReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_tika_grpc_v2_ParseBytesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_tika_grpc_v2_ParseBytesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_tika_grpc_v2_ParseBytesReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_tika_grpc_v2_ParseBytesReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%org/apache/tika/grpc/v2/tika_v2.proto\022" +
      "\027org.apache.tika.grpc.v2\032&org/apache/tik" +
      "a/grpc/v2/document.proto\"\223\001\n\024FetchAndPar" +
      "seRequest\022\022\n\nfetcher_id\030\001 \001(\t\022\021\n\tfetch_k" +
      "ey\030\002 \001(\t\022$\n\034additional_fetch_config_json" +
      "\030\003 \001(\t\022\022\n\nemitter_id\030\004 \001(\t\022\032\n\022parse_cont" +
      "ext_json\030\005 \001(\t\"\\\n\022FetchAndParseReply\022\021\n\t" +
      "fetch_key\030\001 \001(\t\0223\n\010document\030\002 \001(\0132!.org." +
      "apache.tika.grpc.v2.Document\"\277\001\n\021ParseBy" +
      "tesRequest\022\026\n\016correlation_id\030\001 \001(\t\022\017\n\007co" +
      "ntent\030\002 \001(\014\022\025\n\rresource_name\030\003 \001(\t\022\022\n\nso" +
      "urce_uri\030\004 \001(\t\022\025\n\reffective_uri\030\005 \001(\t\022\020\n" +
      "\010base_uri\030\006 \001(\t\022\021\n\ttruncated\030\007 \001(\010\022\032\n\022pa" +
      "rse_context_json\030\010 \001(\t\"^\n\017ParseBytesRepl" +
      "y\022\026\n\016correlation_id\030\001 \001(\t\0223\n\010document\030\002 " +
      "\001(\0132!.org.apache.tika.grpc.v2.Document2\354" +
      "\003\n\006TikaV2\022m\n\rFetchAndParse\022-.org.apache." +
      "tika.grpc.v2.FetchAndParseRequest\032+.org." +
      "apache.tika.grpc.v2.FetchAndParseReply\"\000" +
      "\022\202\001\n FetchAndParseServerSideStreaming\022-." +
      "org.apache.tika.grpc.v2.FetchAndParseReq" +
      "uest\032+.org.apache.tika.grpc.v2.FetchAndP" +
      "arseReply\"\0000\001\022\207\001\n#FetchAndParseBiDirecti" +
      "onalStreaming\022-.org.apache.tika.grpc.v2." +
      "FetchAndParseRequest\032+.org.apache.tika.g" +
      "rpc.v2.FetchAndParseReply\"\000(\0010\001\022d\n\nParse" +
      "Bytes\022*.org.apache.tika.grpc.v2.ParseByt" +
      "esRequest\032(.org.apache.tika.grpc.v2.Pars" +
      "eBytesReply\"\000B(\n\027org.apache.tika.grpc.v2" +
      "B\013TikaV2ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.apache.tika.grpc.v2.DocumentOuterClass.getDescriptor(),
        });
    internal_static_org_apache_tika_grpc_v2_FetchAndParseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_apache_tika_grpc_v2_FetchAndParseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_tika_grpc_v2_FetchAndParseRequest_descriptor,
        new java.lang.String[] { "FetcherId", "FetchKey", "AdditionalFetchConfigJson", "EmitterId", "ParseContextJson", });
    internal_static_org_apache_tika_grpc_v2_FetchAndParseReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_apache_tika_grpc_v2_FetchAndParseReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_tika_grpc_v2_FetchAndParseReply_descriptor,
        new java.lang.String[] { "FetchKey", "Document", });
    internal_static_org_apache_tika_grpc_v2_ParseBytesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_apache_tika_grpc_v2_ParseBytesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_tika_grpc_v2_ParseBytesRequest_descriptor,
        new java.lang.String[] { "CorrelationId", "Content", "ResourceName", "SourceUri", "EffectiveUri", "BaseUri", "Truncated", "ParseContextJson", });
    internal_static_org_apache_tika_grpc_v2_ParseBytesReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_apache_tika_grpc_v2_ParseBytesReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_tika_grpc_v2_ParseBytesReply_descriptor,
        new java.lang.String[] { "CorrelationId", "Document", });
    org.apache.tika.grpc.v2.DocumentOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
